// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: outing-event.proto

package outingproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for OutingEvent service

type OutingEventService interface {
	ChangeAllServiceNodes(ctx context.Context, in *Empty, opts ...client.CallOption) (*Empty, error)
}

type outingEventService struct {
	c    client.Client
	name string
}

func NewOutingEventService(name string, c client.Client) OutingEventService {
	return &outingEventService{
		c:    c,
		name: name,
	}
}

func (c *outingEventService) ChangeAllServiceNodes(ctx context.Context, in *Empty, opts ...client.CallOption) (*Empty, error) {
	req := c.c.NewRequest(c.name, "OutingEvent.ChangeAllServiceNodes", in)
	out := new(Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for OutingEvent service

type OutingEventHandler interface {
	ChangeAllServiceNodes(context.Context, *Empty, *Empty) error
}

func RegisterOutingEventHandler(s server.Server, hdlr OutingEventHandler, opts ...server.HandlerOption) error {
	type outingEvent interface {
		ChangeAllServiceNodes(ctx context.Context, in *Empty, out *Empty) error
	}
	type OutingEvent struct {
		outingEvent
	}
	h := &outingEventHandler{hdlr}
	return s.Handle(s.NewHandler(&OutingEvent{h}, opts...))
}

type outingEventHandler struct {
	OutingEventHandler
}

func (h *outingEventHandler) ChangeAllServiceNodes(ctx context.Context, in *Empty, out *Empty) error {
	return h.OutingEventHandler.ChangeAllServiceNodes(ctx, in, out)
}
