# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: outing-parents.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='outing-parents.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z\r.;outingproto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14outing-parents.proto\"/\n\x17GetOutingByOCodeRequest\x12\x14\n\x0c\x63onfirm_code\x18\x01 \x01(\t\"\xbe\x01\n\x18GetOutingByOCodeResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x0b\n\x03msg\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x11\n\touting_id\x18\x05 \x01(\t\x12\x12\n\nstart_time\x18\x06 \x01(\x03\x12\x10\n\x08\x65nd_time\x18\x07 \x01(\x03\x12\r\n\x05place\x18\x08 \x01(\t\x12\x0e\n\x06reason\x18\t \x01(\t\x12\x11\n\tsituation\x18\n \x01(\t\"3\n\x1b\x43onfirmOutingByOCodeRequest\x12\x14\n\x0c\x63onfirm_code\x18\x01 \x01(\t\"I\n\x1c\x43onfirmOutingByOCodeResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x0b\n\x03msg\x18\x03 \x01(\t2\x81\x02\n\rOutingParents\x12S\n\x14\x41pproveOutingByOCode\x12\x1c.ConfirmOutingByOCodeRequest\x1a\x1d.ConfirmOutingByOCodeResponse\x12R\n\x13RejectOutingByOCode\x12\x1c.ConfirmOutingByOCodeRequest\x1a\x1d.ConfirmOutingByOCodeResponse\x12G\n\x10GetOutingByOCode\x12\x18.GetOutingByOCodeRequest\x1a\x19.GetOutingByOCodeResponseB\x0fZ\r.;outingprotob\x06proto3'
)




_GETOUTINGBYOCODEREQUEST = _descriptor.Descriptor(
  name='GetOutingByOCodeRequest',
  full_name='GetOutingByOCodeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='confirm_code', full_name='GetOutingByOCodeRequest.confirm_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=71,
)


_GETOUTINGBYOCODERESPONSE = _descriptor.Descriptor(
  name='GetOutingByOCodeResponse',
  full_name='GetOutingByOCodeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='GetOutingByOCodeResponse.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='GetOutingByOCodeResponse.code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='GetOutingByOCodeResponse.msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='GetOutingByOCodeResponse.name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='outing_id', full_name='GetOutingByOCodeResponse.outing_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='GetOutingByOCodeResponse.start_time', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='GetOutingByOCodeResponse.end_time', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='place', full_name='GetOutingByOCodeResponse.place', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reason', full_name='GetOutingByOCodeResponse.reason', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='situation', full_name='GetOutingByOCodeResponse.situation', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=264,
)


_CONFIRMOUTINGBYOCODEREQUEST = _descriptor.Descriptor(
  name='ConfirmOutingByOCodeRequest',
  full_name='ConfirmOutingByOCodeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='confirm_code', full_name='ConfirmOutingByOCodeRequest.confirm_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=317,
)


_CONFIRMOUTINGBYOCODERESPONSE = _descriptor.Descriptor(
  name='ConfirmOutingByOCodeResponse',
  full_name='ConfirmOutingByOCodeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ConfirmOutingByOCodeResponse.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='ConfirmOutingByOCodeResponse.code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='ConfirmOutingByOCodeResponse.msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=319,
  serialized_end=392,
)

DESCRIPTOR.message_types_by_name['GetOutingByOCodeRequest'] = _GETOUTINGBYOCODEREQUEST
DESCRIPTOR.message_types_by_name['GetOutingByOCodeResponse'] = _GETOUTINGBYOCODERESPONSE
DESCRIPTOR.message_types_by_name['ConfirmOutingByOCodeRequest'] = _CONFIRMOUTINGBYOCODEREQUEST
DESCRIPTOR.message_types_by_name['ConfirmOutingByOCodeResponse'] = _CONFIRMOUTINGBYOCODERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetOutingByOCodeRequest = _reflection.GeneratedProtocolMessageType('GetOutingByOCodeRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETOUTINGBYOCODEREQUEST,
  '__module__' : 'outing_parents_pb2'
  # @@protoc_insertion_point(class_scope:GetOutingByOCodeRequest)
  })
_sym_db.RegisterMessage(GetOutingByOCodeRequest)

GetOutingByOCodeResponse = _reflection.GeneratedProtocolMessageType('GetOutingByOCodeResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETOUTINGBYOCODERESPONSE,
  '__module__' : 'outing_parents_pb2'
  # @@protoc_insertion_point(class_scope:GetOutingByOCodeResponse)
  })
_sym_db.RegisterMessage(GetOutingByOCodeResponse)

ConfirmOutingByOCodeRequest = _reflection.GeneratedProtocolMessageType('ConfirmOutingByOCodeRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONFIRMOUTINGBYOCODEREQUEST,
  '__module__' : 'outing_parents_pb2'
  # @@protoc_insertion_point(class_scope:ConfirmOutingByOCodeRequest)
  })
_sym_db.RegisterMessage(ConfirmOutingByOCodeRequest)

ConfirmOutingByOCodeResponse = _reflection.GeneratedProtocolMessageType('ConfirmOutingByOCodeResponse', (_message.Message,), {
  'DESCRIPTOR' : _CONFIRMOUTINGBYOCODERESPONSE,
  '__module__' : 'outing_parents_pb2'
  # @@protoc_insertion_point(class_scope:ConfirmOutingByOCodeResponse)
  })
_sym_db.RegisterMessage(ConfirmOutingByOCodeResponse)


DESCRIPTOR._options = None

_OUTINGPARENTS = _descriptor.ServiceDescriptor(
  name='OutingParents',
  full_name='OutingParents',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=395,
  serialized_end=652,
  methods=[
  _descriptor.MethodDescriptor(
    name='ApproveOutingByOCode',
    full_name='OutingParents.ApproveOutingByOCode',
    index=0,
    containing_service=None,
    input_type=_CONFIRMOUTINGBYOCODEREQUEST,
    output_type=_CONFIRMOUTINGBYOCODERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RejectOutingByOCode',
    full_name='OutingParents.RejectOutingByOCode',
    index=1,
    containing_service=None,
    input_type=_CONFIRMOUTINGBYOCODEREQUEST,
    output_type=_CONFIRMOUTINGBYOCODERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetOutingByOCode',
    full_name='OutingParents.GetOutingByOCode',
    index=2,
    containing_service=None,
    input_type=_GETOUTINGBYOCODEREQUEST,
    output_type=_GETOUTINGBYOCODERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_OUTINGPARENTS)

DESCRIPTOR.services_by_name['OutingParents'] = _OUTINGPARENTS

# @@protoc_insertion_point(module_scope)
