# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: outing-parent.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='outing-parent.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13outing-parent.proto\"-\n\x1b\x41pproveOutingByOCodeRequest\x12\x0e\n\x06o_code\x18\x02 \x01(\t\"I\n\x1c\x41pproveOutingByOCodeResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x0b\n\x03msg\x18\x03 \x01(\t2e\n\x0cOutingParent\x12U\n\x14\x41pproveOutingByOCode\x12\x1c.ApproveOutingByOCodeRequest\x1a\x1d.ApproveOutingByOCodeResponse\"\x00\x62\x06proto3'
)




_APPROVEOUTINGBYOCODEREQUEST = _descriptor.Descriptor(
  name='ApproveOutingByOCodeRequest',
  full_name='ApproveOutingByOCodeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='o_code', full_name='ApproveOutingByOCodeRequest.o_code', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=68,
)


_APPROVEOUTINGBYOCODERESPONSE = _descriptor.Descriptor(
  name='ApproveOutingByOCodeResponse',
  full_name='ApproveOutingByOCodeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ApproveOutingByOCodeResponse.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='ApproveOutingByOCodeResponse.code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='ApproveOutingByOCodeResponse.msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=143,
)

DESCRIPTOR.message_types_by_name['ApproveOutingByOCodeRequest'] = _APPROVEOUTINGBYOCODEREQUEST
DESCRIPTOR.message_types_by_name['ApproveOutingByOCodeResponse'] = _APPROVEOUTINGBYOCODERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ApproveOutingByOCodeRequest = _reflection.GeneratedProtocolMessageType('ApproveOutingByOCodeRequest', (_message.Message,), {
  'DESCRIPTOR' : _APPROVEOUTINGBYOCODEREQUEST,
  '__module__' : 'outing_parent_pb2'
  # @@protoc_insertion_point(class_scope:ApproveOutingByOCodeRequest)
  })
_sym_db.RegisterMessage(ApproveOutingByOCodeRequest)

ApproveOutingByOCodeResponse = _reflection.GeneratedProtocolMessageType('ApproveOutingByOCodeResponse', (_message.Message,), {
  'DESCRIPTOR' : _APPROVEOUTINGBYOCODERESPONSE,
  '__module__' : 'outing_parent_pb2'
  # @@protoc_insertion_point(class_scope:ApproveOutingByOCodeResponse)
  })
_sym_db.RegisterMessage(ApproveOutingByOCodeResponse)



_OUTINGPARENT = _descriptor.ServiceDescriptor(
  name='OutingParent',
  full_name='OutingParent',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=145,
  serialized_end=246,
  methods=[
  _descriptor.MethodDescriptor(
    name='ApproveOutingByOCode',
    full_name='OutingParent.ApproveOutingByOCode',
    index=0,
    containing_service=None,
    input_type=_APPROVEOUTINGBYOCODEREQUEST,
    output_type=_APPROVEOUTINGBYOCODERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_OUTINGPARENT)

DESCRIPTOR.services_by_name['OutingParent'] = _OUTINGPARENT

# @@protoc_insertion_point(module_scope)
