// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: announcement-event.proto

package announcementproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for AnnouncementEvent service

type AnnouncementEventService interface {
	ChangeAllServiceNodes(ctx context.Context, in *Empty, opts ...client.CallOption) (*Empty, error)
}

type announcementEventService struct {
	c    client.Client
	name string
}

func NewAnnouncementEventService(name string, c client.Client) AnnouncementEventService {
	return &announcementEventService{
		c:    c,
		name: name,
	}
}

func (c *announcementEventService) ChangeAllServiceNodes(ctx context.Context, in *Empty, opts ...client.CallOption) (*Empty, error) {
	req := c.c.NewRequest(c.name, "AnnouncementEvent.ChangeAllServiceNodes", in)
	out := new(Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AnnouncementEvent service

type AnnouncementEventHandler interface {
	ChangeAllServiceNodes(context.Context, *Empty, *Empty) error
}

func RegisterAnnouncementEventHandler(s server.Server, hdlr AnnouncementEventHandler, opts ...server.HandlerOption) error {
	type announcementEvent interface {
		ChangeAllServiceNodes(ctx context.Context, in *Empty, out *Empty) error
	}
	type AnnouncementEvent struct {
		announcementEvent
	}
	h := &announcementEventHandler{hdlr}
	return s.Handle(s.NewHandler(&AnnouncementEvent{h}, opts...))
}

type announcementEventHandler struct {
	AnnouncementEventHandler
}

func (h *announcementEventHandler) ChangeAllServiceNodes(ctx context.Context, in *Empty, out *Empty) error {
	return h.AnnouncementEventHandler.ChangeAllServiceNodes(ctx, in, out)
}
