// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.1
// 	protoc        v3.11.4
// source: club-student.proto

package clubproto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetClubsSortByUpdateTimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UUID  string `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`    // API를 호출한 학생 계정의 UUID (20자)
	Start uint32 `protobuf:"varint,2,opt,name=Start,proto3" json:"Start,omitempty"` // 페이징의 offset 값
	Count uint32 `protobuf:"varint,3,opt,name=Count,proto3" json:"Count,omitempty"` // 페이징의 limit 값
	Field string `protobuf:"bytes,4,opt,name=Field,proto3" json:"Field,omitempty"`  // 필터링의 Field 값
	Name  string `protobuf:"bytes,5,opt,name=Name,proto3" json:"Name,omitempty"`    // 필터링의 Name 값
}

func (x *GetClubsSortByUpdateTimeRequest) Reset() {
	*x = GetClubsSortByUpdateTimeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_student_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetClubsSortByUpdateTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClubsSortByUpdateTimeRequest) ProtoMessage() {}

func (x *GetClubsSortByUpdateTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_club_student_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClubsSortByUpdateTimeRequest.ProtoReflect.Descriptor instead.
func (*GetClubsSortByUpdateTimeRequest) Descriptor() ([]byte, []int) {
	return file_club_student_proto_rawDescGZIP(), []int{0}
}

func (x *GetClubsSortByUpdateTimeRequest) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *GetClubsSortByUpdateTimeRequest) GetStart() uint32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *GetClubsSortByUpdateTimeRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetClubsSortByUpdateTimeRequest) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *GetClubsSortByUpdateTimeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetClubsSortByUpdateTimeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  uint32        `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`  // 상태 코드
	Code    int32         `protobuf:"zigzag32,2,opt,name=Code,proto3" json:"Code,omitempty"`    // 세부 코드
	Message string        `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"` // 세부 설명
	Clubs   []*ClubInform `protobuf:"bytes,4,rep,name=Clubs,proto3" json:"Clubs,omitempty"`     // 동아리 정보 리스트
}

func (x *GetClubsSortByUpdateTimeResponse) Reset() {
	*x = GetClubsSortByUpdateTimeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_student_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetClubsSortByUpdateTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClubsSortByUpdateTimeResponse) ProtoMessage() {}

func (x *GetClubsSortByUpdateTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_club_student_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClubsSortByUpdateTimeResponse.ProtoReflect.Descriptor instead.
func (*GetClubsSortByUpdateTimeResponse) Descriptor() ([]byte, []int) {
	return file_club_student_proto_rawDescGZIP(), []int{1}
}

func (x *GetClubsSortByUpdateTimeResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetClubsSortByUpdateTimeResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetClubsSortByUpdateTimeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetClubsSortByUpdateTimeResponse) GetClubs() []*ClubInform {
	if x != nil {
		return x.Clubs
	}
	return nil
}

type ClubInform struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClubUUID        string `protobuf:"bytes,1,opt,name=ClubUUID,proto3" json:"ClubUUID,omitempty"`               // 동아리 UUID
	Name            string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`                       // 동아리 이름
	Location        string `protobuf:"bytes,3,opt,name=Location,proto3" json:"Location,omitempty"`               // 동아리실 위치
	Floor           uint32 `protobuf:"varint,4,opt,name=Floor,proto3" json:"Floor,omitempty"`                    // 동아리실 층
	ClubConcept     string `protobuf:"bytes,5,opt,name=ClubConcept,proto3" json:"ClubConcept,omitempty"`         // 동아리 한줄 소개
	LeaderName      string `protobuf:"bytes,6,opt,name=LeaderName,proto3" json:"LeaderName,omitempty"`           // 동아리장 이름
	Field           string `protobuf:"bytes,7,opt,name=Field,proto3" json:"Field,omitempty"`                     // 동아리 분야
	LogoURI         string `protobuf:"bytes,8,opt,name=LogoURI,proto3" json:"LogoURI,omitempty"`                 // 동아리 로고 URI
	RecruitmentUUID string `protobuf:"bytes,9,opt,name=RecruitmentUUID,proto3" json:"RecruitmentUUID,omitempty"` // 해당 동아리가 올린 모집 UUID
}

func (x *ClubInform) Reset() {
	*x = ClubInform{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_student_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClubInform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClubInform) ProtoMessage() {}

func (x *ClubInform) ProtoReflect() protoreflect.Message {
	mi := &file_club_student_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClubInform.ProtoReflect.Descriptor instead.
func (*ClubInform) Descriptor() ([]byte, []int) {
	return file_club_student_proto_rawDescGZIP(), []int{2}
}

func (x *ClubInform) GetClubUUID() string {
	if x != nil {
		return x.ClubUUID
	}
	return ""
}

func (x *ClubInform) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClubInform) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ClubInform) GetFloor() uint32 {
	if x != nil {
		return x.Floor
	}
	return 0
}

func (x *ClubInform) GetClubConcept() string {
	if x != nil {
		return x.ClubConcept
	}
	return ""
}

func (x *ClubInform) GetLeaderName() string {
	if x != nil {
		return x.LeaderName
	}
	return ""
}

func (x *ClubInform) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ClubInform) GetLogoURI() string {
	if x != nil {
		return x.LogoURI
	}
	return ""
}

func (x *ClubInform) GetRecruitmentUUID() string {
	if x != nil {
		return x.RecruitmentUUID
	}
	return ""
}

type GetRecruitmentsSortByCreateTimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UUID  string `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`    // API를 호출한 학생 계정의 UUID (20자)
	Start uint32 `protobuf:"varint,2,opt,name=Start,proto3" json:"Start,omitempty"` // 페이징의 offset 값
	Count uint32 `protobuf:"varint,3,opt,name=Count,proto3" json:"Count,omitempty"` // 페이징의 limit 값
	Field string `protobuf:"bytes,4,opt,name=Field,proto3" json:"Field,omitempty"`  // 필터링의 Field 값
	Name  string `protobuf:"bytes,5,opt,name=Name,proto3" json:"Name,omitempty"`    // 필터링의 Name 값
}

func (x *GetRecruitmentsSortByCreateTimeRequest) Reset() {
	*x = GetRecruitmentsSortByCreateTimeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_student_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRecruitmentsSortByCreateTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecruitmentsSortByCreateTimeRequest) ProtoMessage() {}

func (x *GetRecruitmentsSortByCreateTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_club_student_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecruitmentsSortByCreateTimeRequest.ProtoReflect.Descriptor instead.
func (*GetRecruitmentsSortByCreateTimeRequest) Descriptor() ([]byte, []int) {
	return file_club_student_proto_rawDescGZIP(), []int{3}
}

func (x *GetRecruitmentsSortByCreateTimeRequest) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *GetRecruitmentsSortByCreateTimeRequest) GetStart() uint32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *GetRecruitmentsSortByCreateTimeRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetRecruitmentsSortByCreateTimeRequest) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *GetRecruitmentsSortByCreateTimeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetRecruitmentsSortByCreateTimeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status       uint32               `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`            // 상태 코드
	Code         int32                `protobuf:"zigzag32,2,opt,name=Code,proto3" json:"Code,omitempty"`              // 세부 코드
	Message      string               `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`           // 세부 설명
	Recruitments []*RecruitmentInform `protobuf:"bytes,4,rep,name=Recruitments,proto3" json:"Recruitments,omitempty"` // 동아리 정보 리스트
}

func (x *GetRecruitmentsSortByCreateTimeResponse) Reset() {
	*x = GetRecruitmentsSortByCreateTimeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_student_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRecruitmentsSortByCreateTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecruitmentsSortByCreateTimeResponse) ProtoMessage() {}

func (x *GetRecruitmentsSortByCreateTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_club_student_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecruitmentsSortByCreateTimeResponse.ProtoReflect.Descriptor instead.
func (*GetRecruitmentsSortByCreateTimeResponse) Descriptor() ([]byte, []int) {
	return file_club_student_proto_rawDescGZIP(), []int{4}
}

func (x *GetRecruitmentsSortByCreateTimeResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetRecruitmentsSortByCreateTimeResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetRecruitmentsSortByCreateTimeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetRecruitmentsSortByCreateTimeResponse) GetRecruitments() []*RecruitmentInform {
	if x != nil {
		return x.Recruitments
	}
	return nil
}

type RecruitmentInform struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecruitmentUUID string           `protobuf:"bytes,1,opt,name=RecruitmentUUID,proto3" json:"RecruitmentUUID,omitempty"` // 모집 공고 UUID
	Name            string           `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`                       // 동아리 이름
	RecruitConcept  string           `protobuf:"bytes,3,opt,name=RecruitConcept,proto3" json:"RecruitConcept,omitempty"`   // 모집 공고 한줄 소개
	Location        string           `protobuf:"bytes,4,opt,name=Location,proto3" json:"Location,omitempty"`               // 동아리 위치
	Floor           uint32           `protobuf:"varint,5,opt,name=Floor,proto3" json:"Floor,omitempty"`                    // 동아리실 층
	RecruitMembers  []*RecruitMember `protobuf:"bytes,6,rep,name=RecruitMembers,proto3" json:"RecruitMembers,omitempty"`   // 동아리 모집 분야 리스트
	Field           string           `protobuf:"bytes,7,opt,name=Field,proto3" json:"Field,omitempty"`                     // 동아리 분야
	StartPeriod     string           `protobuf:"bytes,8,opt,name=StartPeriod,proto3" json:"StartPeriod,omitempty"`         // 시작 기간
	EndPeriod       string           `protobuf:"bytes,9,opt,name=EndPeriod,proto3" json:"EndPeriod,omitempty"`             // 종료 기간
	ClubUUID        string           `protobuf:"bytes,10,opt,name=ClubUUID,proto3" json:"ClubUUID,omitempty"`              // 해당 모집을 올린 동아리 UUID
}

func (x *RecruitmentInform) Reset() {
	*x = RecruitmentInform{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_student_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecruitmentInform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecruitmentInform) ProtoMessage() {}

func (x *RecruitmentInform) ProtoReflect() protoreflect.Message {
	mi := &file_club_student_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecruitmentInform.ProtoReflect.Descriptor instead.
func (*RecruitmentInform) Descriptor() ([]byte, []int) {
	return file_club_student_proto_rawDescGZIP(), []int{5}
}

func (x *RecruitmentInform) GetRecruitmentUUID() string {
	if x != nil {
		return x.RecruitmentUUID
	}
	return ""
}

func (x *RecruitmentInform) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RecruitmentInform) GetRecruitConcept() string {
	if x != nil {
		return x.RecruitConcept
	}
	return ""
}

func (x *RecruitmentInform) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *RecruitmentInform) GetFloor() uint32 {
	if x != nil {
		return x.Floor
	}
	return 0
}

func (x *RecruitmentInform) GetRecruitMembers() []*RecruitMember {
	if x != nil {
		return x.RecruitMembers
	}
	return nil
}

func (x *RecruitmentInform) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *RecruitmentInform) GetStartPeriod() string {
	if x != nil {
		return x.StartPeriod
	}
	return ""
}

func (x *RecruitmentInform) GetEndPeriod() string {
	if x != nil {
		return x.EndPeriod
	}
	return ""
}

func (x *RecruitmentInform) GetClubUUID() string {
	if x != nil {
		return x.ClubUUID
	}
	return ""
}

type GetClubInformWithUUIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UUID     string `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`         // API를 호출한 학생 계정의 UUID (20자)
	ClubUUID string `protobuf:"bytes,2,opt,name=ClubUUID,proto3" json:"ClubUUID,omitempty"` // 조회할 동아리의 UUID (17자)
}

func (x *GetClubInformWithUUIDRequest) Reset() {
	*x = GetClubInformWithUUIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_student_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetClubInformWithUUIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClubInformWithUUIDRequest) ProtoMessage() {}

func (x *GetClubInformWithUUIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_club_student_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClubInformWithUUIDRequest.ProtoReflect.Descriptor instead.
func (*GetClubInformWithUUIDRequest) Descriptor() ([]byte, []int) {
	return file_club_student_proto_rawDescGZIP(), []int{6}
}

func (x *GetClubInformWithUUIDRequest) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *GetClubInformWithUUIDRequest) GetClubUUID() string {
	if x != nil {
		return x.ClubUUID
	}
	return ""
}

type GetClubInformWithUUIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status       uint32        `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`            // 상태 코드
	Code         int32         `protobuf:"zigzag32,2,opt,name=Code,proto3" json:"Code,omitempty"`              // 세부 코드
	Message      string        `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`           // 세부 설명
	Name         string        `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`                 // 동아리 이름
	ClubConcept  string        `protobuf:"bytes,5,opt,name=ClubConcept,proto3" json:"ClubConcept,omitempty"`   // 동아리 한줄 소개
	Introduction string        `protobuf:"bytes,6,opt,name=Introduction,proto3" json:"Introduction,omitempty"` // 동아리 설명
	Leader       *ClubMember   `protobuf:"bytes,7,opt,name=Leader,proto3" json:"Leader,omitempty"`             // 동아리장 정보
	ClubMembers  []*ClubMember `protobuf:"bytes,8,rep,name=ClubMembers,proto3" json:"ClubMembers,omitempty"`   // 동아리 부원 리스트
	Location     string        `protobuf:"bytes,9,opt,name=Location,proto3" json:"Location,omitempty"`         // 동아리 위치
	Floor        uint32        `protobuf:"varint,10,opt,name=Floor,proto3" json:"Floor,omitempty"`             // 동아리실 층
	Field        string        `protobuf:"bytes,11,opt,name=Field,proto3" json:"Field,omitempty"`              // 동아리 분야
	LogoURI      string        `protobuf:"bytes,12,opt,name=LogoURI,proto3" json:"LogoURI,omitempty"`          // 동아리 로고 URI
	Link         string        `protobuf:"bytes,13,opt,name=Link,proto3" json:"Link,omitempty"`                // 동아리 페이스북 그룹 링크
}

func (x *GetClubInformWithUUIDResponse) Reset() {
	*x = GetClubInformWithUUIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_student_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetClubInformWithUUIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClubInformWithUUIDResponse) ProtoMessage() {}

func (x *GetClubInformWithUUIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_club_student_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClubInformWithUUIDResponse.ProtoReflect.Descriptor instead.
func (*GetClubInformWithUUIDResponse) Descriptor() ([]byte, []int) {
	return file_club_student_proto_rawDescGZIP(), []int{7}
}

func (x *GetClubInformWithUUIDResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetClubInformWithUUIDResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetClubInformWithUUIDResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetClubInformWithUUIDResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetClubInformWithUUIDResponse) GetClubConcept() string {
	if x != nil {
		return x.ClubConcept
	}
	return ""
}

func (x *GetClubInformWithUUIDResponse) GetIntroduction() string {
	if x != nil {
		return x.Introduction
	}
	return ""
}

func (x *GetClubInformWithUUIDResponse) GetLeader() *ClubMember {
	if x != nil {
		return x.Leader
	}
	return nil
}

func (x *GetClubInformWithUUIDResponse) GetClubMembers() []*ClubMember {
	if x != nil {
		return x.ClubMembers
	}
	return nil
}

func (x *GetClubInformWithUUIDResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *GetClubInformWithUUIDResponse) GetFloor() uint32 {
	if x != nil {
		return x.Floor
	}
	return 0
}

func (x *GetClubInformWithUUIDResponse) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *GetClubInformWithUUIDResponse) GetLogoURI() string {
	if x != nil {
		return x.LogoURI
	}
	return ""
}

func (x *GetClubInformWithUUIDResponse) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type ClubMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Grade         uint32 `protobuf:"varint,1,opt,name=Grade,proto3" json:"Grade,omitempty"`
	Group         uint32 `protobuf:"varint,2,opt,name=Group,proto3" json:"Group,omitempty"`
	StudentNumber uint32 `protobuf:"varint,3,opt,name=StudentNumber,proto3" json:"StudentNumber,omitempty"`
	Name          string `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *ClubMember) Reset() {
	*x = ClubMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_student_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClubMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClubMember) ProtoMessage() {}

func (x *ClubMember) ProtoReflect() protoreflect.Message {
	mi := &file_club_student_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClubMember.ProtoReflect.Descriptor instead.
func (*ClubMember) Descriptor() ([]byte, []int) {
	return file_club_student_proto_rawDescGZIP(), []int{8}
}

func (x *ClubMember) GetGrade() uint32 {
	if x != nil {
		return x.Grade
	}
	return 0
}

func (x *ClubMember) GetGroup() uint32 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *ClubMember) GetStudentNumber() uint32 {
	if x != nil {
		return x.StudentNumber
	}
	return 0
}

func (x *ClubMember) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetRecruitmentInformWithUUIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UUID            string `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`                       // API를 호출한 학생 계정의 UUID (20자)
	RecruitmentUUID string `protobuf:"bytes,2,opt,name=RecruitmentUUID,proto3" json:"RecruitmentUUID,omitempty"` // 조회할 모집 공고의 UUID (24자)
}

func (x *GetRecruitmentInformWithUUIDRequest) Reset() {
	*x = GetRecruitmentInformWithUUIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_student_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRecruitmentInformWithUUIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecruitmentInformWithUUIDRequest) ProtoMessage() {}

func (x *GetRecruitmentInformWithUUIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_club_student_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecruitmentInformWithUUIDRequest.ProtoReflect.Descriptor instead.
func (*GetRecruitmentInformWithUUIDRequest) Descriptor() ([]byte, []int) {
	return file_club_student_proto_rawDescGZIP(), []int{9}
}

func (x *GetRecruitmentInformWithUUIDRequest) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *GetRecruitmentInformWithUUIDRequest) GetRecruitmentUUID() string {
	if x != nil {
		return x.RecruitmentUUID
	}
	return ""
}

type GetRecruitmentInformWithUUIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status         uint32           `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`                // 상태 코드
	Code           int32            `protobuf:"zigzag32,2,opt,name=Code,proto3" json:"Code,omitempty"`                  // 세부 코드
	Message        string           `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`               // 세부 설명
	ClubUUID       string           `protobuf:"bytes,4,opt,name=ClubUUID,proto3" json:"ClubUUID,omitempty"`             // 해당 모집을 올린 동아리의 UUID
	RecruitConcept string           `protobuf:"bytes,5,opt,name=RecruitConcept,proto3" json:"RecruitConcept,omitempty"` // 모집 컨셉
	RecruitMembers []*RecruitMember `protobuf:"bytes,6,rep,name=RecruitMembers,proto3" json:"RecruitMembers,omitempty"` // 모집 멤버 리스트
	StartPeriod    string           `protobuf:"bytes,7,opt,name=StartPeriod,proto3" json:"StartPeriod,omitempty"`       // 모집 시작 기간
	EndPeriod      string           `protobuf:"bytes,8,opt,name=EndPeriod,proto3" json:"EndPeriod,omitempty"`           // 모집 종료 기간
}

func (x *GetRecruitmentInformWithUUIDResponse) Reset() {
	*x = GetRecruitmentInformWithUUIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_student_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRecruitmentInformWithUUIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecruitmentInformWithUUIDResponse) ProtoMessage() {}

func (x *GetRecruitmentInformWithUUIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_club_student_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecruitmentInformWithUUIDResponse.ProtoReflect.Descriptor instead.
func (*GetRecruitmentInformWithUUIDResponse) Descriptor() ([]byte, []int) {
	return file_club_student_proto_rawDescGZIP(), []int{10}
}

func (x *GetRecruitmentInformWithUUIDResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetRecruitmentInformWithUUIDResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetRecruitmentInformWithUUIDResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetRecruitmentInformWithUUIDResponse) GetClubUUID() string {
	if x != nil {
		return x.ClubUUID
	}
	return ""
}

func (x *GetRecruitmentInformWithUUIDResponse) GetRecruitConcept() string {
	if x != nil {
		return x.RecruitConcept
	}
	return ""
}

func (x *GetRecruitmentInformWithUUIDResponse) GetRecruitMembers() []*RecruitMember {
	if x != nil {
		return x.RecruitMembers
	}
	return nil
}

func (x *GetRecruitmentInformWithUUIDResponse) GetStartPeriod() string {
	if x != nil {
		return x.StartPeriod
	}
	return ""
}

func (x *GetRecruitmentInformWithUUIDResponse) GetEndPeriod() string {
	if x != nil {
		return x.EndPeriod
	}
	return ""
}

type RecruitMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Grade  string `protobuf:"bytes,1,opt,name=Grade,proto3" json:"Grade,omitempty"`
	Field  string `protobuf:"bytes,2,opt,name=Field,proto3" json:"Field,omitempty"`
	Number string `protobuf:"bytes,3,opt,name=Number,proto3" json:"Number,omitempty"`
}

func (x *RecruitMember) Reset() {
	*x = RecruitMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_student_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecruitMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecruitMember) ProtoMessage() {}

func (x *RecruitMember) ProtoReflect() protoreflect.Message {
	mi := &file_club_student_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecruitMember.ProtoReflect.Descriptor instead.
func (*RecruitMember) Descriptor() ([]byte, []int) {
	return file_club_student_proto_rawDescGZIP(), []int{11}
}

func (x *RecruitMember) GetGrade() string {
	if x != nil {
		return x.Grade
	}
	return ""
}

func (x *RecruitMember) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *RecruitMember) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

type GetAllClubFieldsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UUID string `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"` // API를 호출한 학생 계정의 UUID (20자)
}

func (x *GetAllClubFieldsRequest) Reset() {
	*x = GetAllClubFieldsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_student_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllClubFieldsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllClubFieldsRequest) ProtoMessage() {}

func (x *GetAllClubFieldsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_club_student_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllClubFieldsRequest.ProtoReflect.Descriptor instead.
func (*GetAllClubFieldsRequest) Descriptor() ([]byte, []int) {
	return file_club_student_proto_rawDescGZIP(), []int{12}
}

func (x *GetAllClubFieldsRequest) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

type GetAllClubFieldsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  uint32   `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`  // 상태 코드
	Code    int32    `protobuf:"zigzag32,2,opt,name=Code,proto3" json:"Code,omitempty"`    // 세부 코드
	Message string   `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"` // 세부 설명
	Fields  []*Field `protobuf:"bytes,4,rep,name=Fields,proto3" json:"Fields,omitempty"`   // 동아리의 모든 분야 리스트
}

func (x *GetAllClubFieldsResponse) Reset() {
	*x = GetAllClubFieldsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_student_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllClubFieldsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllClubFieldsResponse) ProtoMessage() {}

func (x *GetAllClubFieldsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_club_student_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllClubFieldsResponse.ProtoReflect.Descriptor instead.
func (*GetAllClubFieldsResponse) Descriptor() ([]byte, []int) {
	return file_club_student_proto_rawDescGZIP(), []int{13}
}

func (x *GetAllClubFieldsResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetAllClubFieldsResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetAllClubFieldsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAllClubFieldsResponse) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

type Field struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
}

func (x *Field) Reset() {
	*x = Field{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_student_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_club_student_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_club_student_proto_rawDescGZIP(), []int{14}
}

func (x *Field) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

type GetTotalCountOfClubsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UUID string `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"` // API를 호출한 학생 계정의 UUID (20자)
}

func (x *GetTotalCountOfClubsRequest) Reset() {
	*x = GetTotalCountOfClubsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_student_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTotalCountOfClubsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTotalCountOfClubsRequest) ProtoMessage() {}

func (x *GetTotalCountOfClubsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_club_student_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTotalCountOfClubsRequest.ProtoReflect.Descriptor instead.
func (*GetTotalCountOfClubsRequest) Descriptor() ([]byte, []int) {
	return file_club_student_proto_rawDescGZIP(), []int{15}
}

func (x *GetTotalCountOfClubsRequest) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

type GetTotalCountOfClubsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  uint32 `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`  // 상태 코드
	Code    int32  `protobuf:"zigzag32,2,opt,name=Code,proto3" json:"Code,omitempty"`    // 세부 코드
	Message string `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"` // 세부 설명
	Count   uint32 `protobuf:"varint,4,opt,name=Count,proto3" json:"Count,omitempty"`    // 동아리 총 개수
}

func (x *GetTotalCountOfClubsResponse) Reset() {
	*x = GetTotalCountOfClubsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_student_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTotalCountOfClubsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTotalCountOfClubsResponse) ProtoMessage() {}

func (x *GetTotalCountOfClubsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_club_student_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTotalCountOfClubsResponse.ProtoReflect.Descriptor instead.
func (*GetTotalCountOfClubsResponse) Descriptor() ([]byte, []int) {
	return file_club_student_proto_rawDescGZIP(), []int{16}
}

func (x *GetTotalCountOfClubsResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetTotalCountOfClubsResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetTotalCountOfClubsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetTotalCountOfClubsResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetTotalCountOfRecruitmentsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UUID string `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"` // API를 호출한 학생 계정의 UUID (20자)
}

func (x *GetTotalCountOfRecruitmentsRequest) Reset() {
	*x = GetTotalCountOfRecruitmentsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_student_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTotalCountOfRecruitmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTotalCountOfRecruitmentsRequest) ProtoMessage() {}

func (x *GetTotalCountOfRecruitmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_club_student_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTotalCountOfRecruitmentsRequest.ProtoReflect.Descriptor instead.
func (*GetTotalCountOfRecruitmentsRequest) Descriptor() ([]byte, []int) {
	return file_club_student_proto_rawDescGZIP(), []int{17}
}

func (x *GetTotalCountOfRecruitmentsRequest) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

type GetTotalCountOfRecruitmentsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  uint32 `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`  // 상태 코드
	Code    int32  `protobuf:"zigzag32,2,opt,name=Code,proto3" json:"Code,omitempty"`    // 세부 코드
	Message string `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"` // 세부 설명
	Count   uint32 `protobuf:"varint,4,opt,name=Count,proto3" json:"Count,omitempty"`    // 모집 공고 총 개수
}

func (x *GetTotalCountOfRecruitmentsResponse) Reset() {
	*x = GetTotalCountOfRecruitmentsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_student_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTotalCountOfRecruitmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTotalCountOfRecruitmentsResponse) ProtoMessage() {}

func (x *GetTotalCountOfRecruitmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_club_student_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTotalCountOfRecruitmentsResponse.ProtoReflect.Descriptor instead.
func (*GetTotalCountOfRecruitmentsResponse) Descriptor() ([]byte, []int) {
	return file_club_student_proto_rawDescGZIP(), []int{18}
}

func (x *GetTotalCountOfRecruitmentsResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetTotalCountOfRecruitmentsResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetTotalCountOfRecruitmentsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetTotalCountOfRecruitmentsResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CheckIfClubLeaderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UUID string `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"` // API를 호출한 학생 계정의 UUID (20자)
}

func (x *CheckIfClubLeaderRequest) Reset() {
	*x = CheckIfClubLeaderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_student_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckIfClubLeaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfClubLeaderRequest) ProtoMessage() {}

func (x *CheckIfClubLeaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_club_student_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfClubLeaderRequest.ProtoReflect.Descriptor instead.
func (*CheckIfClubLeaderRequest) Descriptor() ([]byte, []int) {
	return file_club_student_proto_rawDescGZIP(), []int{19}
}

func (x *CheckIfClubLeaderRequest) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

type CheckIfClubLeaderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   uint32 `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`    // 상태 코드
	Code     int32  `protobuf:"zigzag32,2,opt,name=Code,proto3" json:"Code,omitempty"`      // 세부 코드
	Message  string `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`   // 세부 설명
	ClubUUID string `protobuf:"bytes,4,opt,name=ClubUUID,proto3" json:"ClubUUID,omitempty"` // 본인이 동아리 장인 동아리의 UUID
}

func (x *CheckIfClubLeaderResponse) Reset() {
	*x = CheckIfClubLeaderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_student_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckIfClubLeaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfClubLeaderResponse) ProtoMessage() {}

func (x *CheckIfClubLeaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_club_student_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfClubLeaderResponse.ProtoReflect.Descriptor instead.
func (*CheckIfClubLeaderResponse) Descriptor() ([]byte, []int) {
	return file_club_student_proto_rawDescGZIP(), []int{20}
}

func (x *CheckIfClubLeaderResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CheckIfClubLeaderResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CheckIfClubLeaderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CheckIfClubLeaderResponse) GetClubUUID() string {
	if x != nil {
		return x.ClubUUID
	}
	return ""
}

var File_club_student_proto protoreflect.FileDescriptor

var file_club_student_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x6c, 0x75, 0x62, 0x2d, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8b, 0x01, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x75, 0x62,
	0x73, 0x53, 0x6f, 0x72, 0x74, 0x42, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x8b, 0x01, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x75, 0x62, 0x73, 0x53,
	0x6f, 0x72, 0x74, 0x42, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x11, 0x52, 0x04, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a,
	0x05, 0x43, 0x6c, 0x75, 0x62, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x43,
	0x6c, 0x75, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x05, 0x43, 0x6c, 0x75, 0x62, 0x73,
	0x22, 0x8a, 0x02, 0x0a, 0x0a, 0x43, 0x6c, 0x75, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x12,
	0x1a, 0x0a, 0x08, 0x43, 0x6c, 0x75, 0x62, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x43, 0x6c, 0x75, 0x62, 0x55, 0x55, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x46,
	0x6c, 0x6f, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x46, 0x6c, 0x6f, 0x6f,
	0x72, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x6c, 0x75, 0x62, 0x43, 0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x43, 0x6c, 0x75, 0x62, 0x43, 0x6f, 0x6e, 0x63,
	0x65, 0x70, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x4c, 0x6f, 0x67,
	0x6f, 0x55, 0x52, 0x49, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4c, 0x6f, 0x67, 0x6f,
	0x55, 0x52, 0x49, 0x12, 0x28, 0x0a, 0x0f, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x55, 0x55, 0x49, 0x44, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x52, 0x65,
	0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x55, 0x49, 0x44, 0x22, 0x92, 0x01,
	0x0a, 0x26, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x53, 0x6f, 0x72, 0x74, 0x42, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0xa7, 0x01, 0x0a, 0x27, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x53, 0x6f, 0x72, 0x74, 0x42, 0x79, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x11, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x36, 0x0a, 0x0c, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x52, 0x65, 0x63,
	0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x0c,
	0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0xd5, 0x02, 0x0a,
	0x11, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x72, 0x6d, 0x12, 0x28, 0x0a, 0x0f, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x52, 0x65, 0x63,
	0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x55, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x26, 0x0a, 0x0e, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x43, 0x6f, 0x6e, 0x63, 0x65,
	0x70, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69,
	0x74, 0x43, 0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x12, 0x36, 0x0a, 0x0e, 0x52, 0x65,
	0x63, 0x72, 0x75, 0x69, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x52, 0x0e, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x45, 0x6e,
	0x64, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x45,
	0x6e, 0x64, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6c, 0x75, 0x62,
	0x55, 0x55, 0x49, 0x44, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x6c, 0x75, 0x62,
	0x55, 0x55, 0x49, 0x44, 0x22, 0x4e, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x75, 0x62, 0x49,
	0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x57, 0x69, 0x74, 0x68, 0x55, 0x55, 0x49, 0x44, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6c, 0x75, 0x62,
	0x55, 0x55, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x6c, 0x75, 0x62,
	0x55, 0x55, 0x49, 0x44, 0x22, 0x89, 0x03, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x75, 0x62,
	0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x57, 0x69, 0x74, 0x68, 0x55, 0x55, 0x49, 0x44, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x11, 0x52, 0x04, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x43, 0x6c, 0x75, 0x62, 0x43, 0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x43, 0x6c, 0x75, 0x62, 0x43, 0x6f, 0x6e, 0x63, 0x65,
	0x70, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x06, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x43, 0x6c, 0x75, 0x62, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x52, 0x06, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x2d, 0x0a, 0x0b, 0x43,
	0x6c, 0x75, 0x62, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x43, 0x6c, 0x75, 0x62, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x0b, 0x43,
	0x6c, 0x75, 0x62, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x4c, 0x6f, 0x67, 0x6f, 0x55, 0x52, 0x49, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x4c, 0x6f, 0x67, 0x6f, 0x55, 0x52, 0x49, 0x12, 0x12, 0x0a, 0x04,
	0x4c, 0x69, 0x6e, 0x6b, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4c, 0x69, 0x6e, 0x6b,
	0x22, 0x72, 0x0a, 0x0a, 0x43, 0x6c, 0x75, 0x62, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x47, 0x72, 0x61, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x47,
	0x72, 0x61, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x24, 0x0a, 0x0d, 0x53, 0x74,
	0x75, 0x64, 0x65, 0x6e, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0d, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x63, 0x0a, 0x23, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x72, 0x75,
	0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x57, 0x69, 0x74, 0x68,
	0x55, 0x55, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x55,
	0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12,
	0x28, 0x0a, 0x0f, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x55,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x55, 0x49, 0x44, 0x22, 0xa8, 0x02, 0x0a, 0x24, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x72, 0x6d, 0x57, 0x69, 0x74, 0x68, 0x55, 0x55, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x11, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6c, 0x75, 0x62,
	0x55, 0x55, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x6c, 0x75, 0x62,
	0x55, 0x55, 0x49, 0x44, 0x12, 0x26, 0x0a, 0x0e, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x43,
	0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x52, 0x65,
	0x63, 0x72, 0x75, 0x69, 0x74, 0x43, 0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74, 0x12, 0x36, 0x0a, 0x0e,
	0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x52, 0x0e, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x65, 0x72,
	0x69, 0x6f, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x45, 0x6e, 0x64, 0x50, 0x65, 0x72,
	0x69, 0x6f, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x45, 0x6e, 0x64, 0x50, 0x65,
	0x72, 0x69, 0x6f, 0x64, 0x22, 0x53, 0x0a, 0x0d, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x47, 0x72, 0x61, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x47, 0x72, 0x61, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x2d, 0x0a, 0x17, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x43, 0x6c, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x55, 0x55, 0x49, 0x44, 0x22, 0x80, 0x01, 0x0a, 0x18, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x43, 0x6c, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x11, 0x52, 0x04, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x06, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x52, 0x06, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x1d, 0x0a, 0x05, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x31, 0x0a, 0x1b, 0x47, 0x65,
	0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4f, 0x66, 0x43, 0x6c, 0x75,
	0x62, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x55, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x55, 0x49, 0x44, 0x22, 0x7a, 0x0a,
	0x1c, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4f, 0x66,
	0x43, 0x6c, 0x75, 0x62, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x11, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x38, 0x0a, 0x22, 0x47, 0x65, 0x74,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4f, 0x66, 0x52, 0x65, 0x63, 0x72,
	0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55,
	0x55, 0x49, 0x44, 0x22, 0x81, 0x01, 0x0a, 0x23, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4f, 0x66, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x11, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2e, 0x0a, 0x18, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x49, 0x66, 0x43, 0x6c, 0x75, 0x62, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x55, 0x55, 0x49, 0x44, 0x22, 0x7d, 0x0a, 0x19, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x49, 0x66, 0x43, 0x6c, 0x75, 0x62, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x11, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6c,
	0x75, 0x62, 0x55, 0x55, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x6c,
	0x75, 0x62, 0x55, 0x55, 0x49, 0x44, 0x32, 0x8d, 0x06, 0x0a, 0x0b, 0x43, 0x6c, 0x75, 0x62, 0x53,
	0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x12, 0x61, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x75,
	0x62, 0x73, 0x53, 0x6f, 0x72, 0x74, 0x42, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x20, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x75, 0x62, 0x73, 0x53, 0x6f, 0x72,
	0x74, 0x42, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x75, 0x62, 0x73, 0x53,
	0x6f, 0x72, 0x74, 0x42, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x76, 0x0a, 0x1f, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x53, 0x6f, 0x72, 0x74,
	0x42, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x27, 0x2e, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x53, 0x6f,
	0x72, 0x74, 0x42, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x72, 0x75,
	0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x53, 0x6f, 0x72, 0x74, 0x42, 0x79, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x58, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x75, 0x62, 0x49, 0x6e, 0x66, 0x6f,
	0x72, 0x6d, 0x57, 0x69, 0x74, 0x68, 0x55, 0x55, 0x49, 0x44, 0x12, 0x1d, 0x2e, 0x47, 0x65, 0x74,
	0x43, 0x6c, 0x75, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x57, 0x69, 0x74, 0x68, 0x55, 0x55,
	0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x47, 0x65, 0x74, 0x43,
	0x6c, 0x75, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x57, 0x69, 0x74, 0x68, 0x55, 0x55, 0x49,
	0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6d, 0x0a, 0x1c, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x72, 0x6d, 0x57, 0x69, 0x74, 0x68, 0x55, 0x55, 0x49, 0x44, 0x12, 0x24, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x72, 0x6d, 0x57, 0x69, 0x74, 0x68, 0x55, 0x55, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x25, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x57, 0x69, 0x74, 0x68, 0x55, 0x55, 0x49, 0x44,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x43, 0x6c, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x18,
	0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x6c, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x43, 0x6c, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4f, 0x66, 0x43, 0x6c, 0x75, 0x62, 0x73, 0x12, 0x1c, 0x2e,
	0x47, 0x65, 0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4f, 0x66, 0x43,
	0x6c, 0x75, 0x62, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x47, 0x65,
	0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4f, 0x66, 0x43, 0x6c, 0x75,
	0x62, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6a, 0x0a, 0x1b,
	0x47, 0x65, 0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4f, 0x66, 0x52,
	0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x23, 0x2e, 0x47, 0x65,
	0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4f, 0x66, 0x52, 0x65, 0x63,
	0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x24, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x4f, 0x66, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x11, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x49, 0x66, 0x43, 0x6c, 0x75, 0x62, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x19, 0x2e,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x66, 0x43, 0x6c, 0x75, 0x62, 0x4c, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x49, 0x66, 0x43, 0x6c, 0x75, 0x62, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x3b, 0x63, 0x6c, 0x75, 0x62,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_club_student_proto_rawDescOnce sync.Once
	file_club_student_proto_rawDescData = file_club_student_proto_rawDesc
)

func file_club_student_proto_rawDescGZIP() []byte {
	file_club_student_proto_rawDescOnce.Do(func() {
		file_club_student_proto_rawDescData = protoimpl.X.CompressGZIP(file_club_student_proto_rawDescData)
	})
	return file_club_student_proto_rawDescData
}

var file_club_student_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_club_student_proto_goTypes = []interface{}{
	(*GetClubsSortByUpdateTimeRequest)(nil),         // 0: GetClubsSortByUpdateTimeRequest
	(*GetClubsSortByUpdateTimeResponse)(nil),        // 1: GetClubsSortByUpdateTimeResponse
	(*ClubInform)(nil),                              // 2: ClubInform
	(*GetRecruitmentsSortByCreateTimeRequest)(nil),  // 3: GetRecruitmentsSortByCreateTimeRequest
	(*GetRecruitmentsSortByCreateTimeResponse)(nil), // 4: GetRecruitmentsSortByCreateTimeResponse
	(*RecruitmentInform)(nil),                       // 5: RecruitmentInform
	(*GetClubInformWithUUIDRequest)(nil),            // 6: GetClubInformWithUUIDRequest
	(*GetClubInformWithUUIDResponse)(nil),           // 7: GetClubInformWithUUIDResponse
	(*ClubMember)(nil),                              // 8: ClubMember
	(*GetRecruitmentInformWithUUIDRequest)(nil),     // 9: GetRecruitmentInformWithUUIDRequest
	(*GetRecruitmentInformWithUUIDResponse)(nil),    // 10: GetRecruitmentInformWithUUIDResponse
	(*RecruitMember)(nil),                           // 11: RecruitMember
	(*GetAllClubFieldsRequest)(nil),                 // 12: GetAllClubFieldsRequest
	(*GetAllClubFieldsResponse)(nil),                // 13: GetAllClubFieldsResponse
	(*Field)(nil),                                   // 14: Field
	(*GetTotalCountOfClubsRequest)(nil),             // 15: GetTotalCountOfClubsRequest
	(*GetTotalCountOfClubsResponse)(nil),            // 16: GetTotalCountOfClubsResponse
	(*GetTotalCountOfRecruitmentsRequest)(nil),      // 17: GetTotalCountOfRecruitmentsRequest
	(*GetTotalCountOfRecruitmentsResponse)(nil),     // 18: GetTotalCountOfRecruitmentsResponse
	(*CheckIfClubLeaderRequest)(nil),                // 19: CheckIfClubLeaderRequest
	(*CheckIfClubLeaderResponse)(nil),               // 20: CheckIfClubLeaderResponse
}
var file_club_student_proto_depIdxs = []int32{
	2,  // 0: GetClubsSortByUpdateTimeResponse.Clubs:type_name -> ClubInform
	5,  // 1: GetRecruitmentsSortByCreateTimeResponse.Recruitments:type_name -> RecruitmentInform
	11, // 2: RecruitmentInform.RecruitMembers:type_name -> RecruitMember
	8,  // 3: GetClubInformWithUUIDResponse.Leader:type_name -> ClubMember
	8,  // 4: GetClubInformWithUUIDResponse.ClubMembers:type_name -> ClubMember
	11, // 5: GetRecruitmentInformWithUUIDResponse.RecruitMembers:type_name -> RecruitMember
	14, // 6: GetAllClubFieldsResponse.Fields:type_name -> Field
	0,  // 7: ClubStudent.GetClubsSortByUpdateTime:input_type -> GetClubsSortByUpdateTimeRequest
	3,  // 8: ClubStudent.GetRecruitmentsSortByCreateTime:input_type -> GetRecruitmentsSortByCreateTimeRequest
	6,  // 9: ClubStudent.GetClubInformWithUUID:input_type -> GetClubInformWithUUIDRequest
	9,  // 10: ClubStudent.GetRecruitmentInformWithUUID:input_type -> GetRecruitmentInformWithUUIDRequest
	12, // 11: ClubStudent.GetAllClubFields:input_type -> GetAllClubFieldsRequest
	15, // 12: ClubStudent.GetTotalCountOfClubs:input_type -> GetTotalCountOfClubsRequest
	17, // 13: ClubStudent.GetTotalCountOfRecruitments:input_type -> GetTotalCountOfRecruitmentsRequest
	19, // 14: ClubStudent.CheckIfClubLeader:input_type -> CheckIfClubLeaderRequest
	1,  // 15: ClubStudent.GetClubsSortByUpdateTime:output_type -> GetClubsSortByUpdateTimeResponse
	4,  // 16: ClubStudent.GetRecruitmentsSortByCreateTime:output_type -> GetRecruitmentsSortByCreateTimeResponse
	7,  // 17: ClubStudent.GetClubInformWithUUID:output_type -> GetClubInformWithUUIDResponse
	10, // 18: ClubStudent.GetRecruitmentInformWithUUID:output_type -> GetRecruitmentInformWithUUIDResponse
	13, // 19: ClubStudent.GetAllClubFields:output_type -> GetAllClubFieldsResponse
	16, // 20: ClubStudent.GetTotalCountOfClubs:output_type -> GetTotalCountOfClubsResponse
	18, // 21: ClubStudent.GetTotalCountOfRecruitments:output_type -> GetTotalCountOfRecruitmentsResponse
	20, // 22: ClubStudent.CheckIfClubLeader:output_type -> CheckIfClubLeaderResponse
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_club_student_proto_init() }
func file_club_student_proto_init() {
	if File_club_student_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_club_student_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetClubsSortByUpdateTimeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_student_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetClubsSortByUpdateTimeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_student_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClubInform); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_student_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRecruitmentsSortByCreateTimeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_student_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRecruitmentsSortByCreateTimeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_student_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecruitmentInform); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_student_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetClubInformWithUUIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_student_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetClubInformWithUUIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_student_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClubMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_student_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRecruitmentInformWithUUIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_student_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRecruitmentInformWithUUIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_student_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecruitMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_student_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllClubFieldsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_student_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllClubFieldsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_student_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Field); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_student_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTotalCountOfClubsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_student_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTotalCountOfClubsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_student_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTotalCountOfRecruitmentsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_student_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTotalCountOfRecruitmentsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_student_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckIfClubLeaderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_student_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckIfClubLeaderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_club_student_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_club_student_proto_goTypes,
		DependencyIndexes: file_club_student_proto_depIdxs,
		MessageInfos:      file_club_student_proto_msgTypes,
	}.Build()
	File_club_student_proto = out.File
	file_club_student_proto_rawDesc = nil
	file_club_student_proto_goTypes = nil
	file_club_student_proto_depIdxs = nil
}
