// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.1
// 	protoc        v3.11.4
// source: auth-teacher.proto

package authproto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type LoginTeacherAuthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeacherID string `protobuf:"bytes,1,opt,name=TeacherID,proto3" json:"TeacherID,omitempty"` // 선생님용 계정 아이디 (4~16자 사이)
	TeacherPW string `protobuf:"bytes,2,opt,name=TeacherPW,proto3" json:"TeacherPW,omitempty"` // 선생님용 계정 비밀번호 (4~16자 사이)
}

func (x *LoginTeacherAuthRequest) Reset() {
	*x = LoginTeacherAuthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_teacher_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginTeacherAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginTeacherAuthRequest) ProtoMessage() {}

func (x *LoginTeacherAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_teacher_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginTeacherAuthRequest.ProtoReflect.Descriptor instead.
func (*LoginTeacherAuthRequest) Descriptor() ([]byte, []int) {
	return file_auth_teacher_proto_rawDescGZIP(), []int{0}
}

func (x *LoginTeacherAuthRequest) GetTeacherID() string {
	if x != nil {
		return x.TeacherID
	}
	return ""
}

func (x *LoginTeacherAuthRequest) GetTeacherPW() string {
	if x != nil {
		return x.TeacherPW
	}
	return ""
}

type LoginTeacherAuthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status              uint32 `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`                          // 상태 코드
	Code                int32  `protobuf:"zigzag32,2,opt,name=Code,proto3" json:"Code,omitempty"`                            // 세부 코드
	Message             string `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`                         // 세부 설명
	AccessToken         string `protobuf:"bytes,4,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`                 // 선생님 계정 인증을 위한 JWT
	LoggedInTeacherUUID string `protobuf:"bytes,5,opt,name=LoggedInTeacherUUID,proto3" json:"LoggedInTeacherUUID,omitempty"` // 로그인한 선생님 계정의 uuid
}

func (x *LoginTeacherAuthResponse) Reset() {
	*x = LoginTeacherAuthResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_teacher_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginTeacherAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginTeacherAuthResponse) ProtoMessage() {}

func (x *LoginTeacherAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_teacher_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginTeacherAuthResponse.ProtoReflect.Descriptor instead.
func (*LoginTeacherAuthResponse) Descriptor() ([]byte, []int) {
	return file_auth_teacher_proto_rawDescGZIP(), []int{1}
}

func (x *LoginTeacherAuthResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *LoginTeacherAuthResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LoginTeacherAuthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginTeacherAuthResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginTeacherAuthResponse) GetLoggedInTeacherUUID() string {
	if x != nil {
		return x.LoggedInTeacherUUID
	}
	return ""
}

type ChangeTeacherPWRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UUID        string `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`               // API를 호출한 선생님 계정의 uuid (20자)
	TeacherUUID string `protobuf:"bytes,2,opt,name=TeacherUUID,proto3" json:"TeacherUUID,omitempty"` // 변경할 선생님 계정의 uuid (20자)
	CurrentPW   string `protobuf:"bytes,3,opt,name=CurrentPW,proto3" json:"CurrentPW,omitempty"`     // 해당 사용자의 현재 PW (4~16 사이)
	RevisionPW  string `protobuf:"bytes,4,opt,name=RevisionPW,proto3" json:"RevisionPW,omitempty"`   // 변경할 PW (4~16 사이)
}

func (x *ChangeTeacherPWRequest) Reset() {
	*x = ChangeTeacherPWRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_teacher_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeTeacherPWRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeTeacherPWRequest) ProtoMessage() {}

func (x *ChangeTeacherPWRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_teacher_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeTeacherPWRequest.ProtoReflect.Descriptor instead.
func (*ChangeTeacherPWRequest) Descriptor() ([]byte, []int) {
	return file_auth_teacher_proto_rawDescGZIP(), []int{2}
}

func (x *ChangeTeacherPWRequest) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *ChangeTeacherPWRequest) GetTeacherUUID() string {
	if x != nil {
		return x.TeacherUUID
	}
	return ""
}

func (x *ChangeTeacherPWRequest) GetCurrentPW() string {
	if x != nil {
		return x.CurrentPW
	}
	return ""
}

func (x *ChangeTeacherPWRequest) GetRevisionPW() string {
	if x != nil {
		return x.RevisionPW
	}
	return ""
}

type ChangeTeacherPWResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  uint32 `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`  // 상태 코드
	Code    int32  `protobuf:"zigzag32,2,opt,name=Code,proto3" json:"Code,omitempty"`    // 세부 코드
	Message string `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"` // 세부 설명
}

func (x *ChangeTeacherPWResponse) Reset() {
	*x = ChangeTeacherPWResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_teacher_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeTeacherPWResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeTeacherPWResponse) ProtoMessage() {}

func (x *ChangeTeacherPWResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_teacher_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeTeacherPWResponse.ProtoReflect.Descriptor instead.
func (*ChangeTeacherPWResponse) Descriptor() ([]byte, []int) {
	return file_auth_teacher_proto_rawDescGZIP(), []int{3}
}

func (x *ChangeTeacherPWResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ChangeTeacherPWResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ChangeTeacherPWResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetTeacherInformWithUUIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UUID        string `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`               // API를 호출한 학생 계정의 uuid (20자)
	TeacherUUID string `protobuf:"bytes,2,opt,name=TeacherUUID,proto3" json:"TeacherUUID,omitempty"` // 조회할 선생님 계정의 uuid (20자)
}

func (x *GetTeacherInformWithUUIDRequest) Reset() {
	*x = GetTeacherInformWithUUIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_teacher_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTeacherInformWithUUIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeacherInformWithUUIDRequest) ProtoMessage() {}

func (x *GetTeacherInformWithUUIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_teacher_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeacherInformWithUUIDRequest.ProtoReflect.Descriptor instead.
func (*GetTeacherInformWithUUIDRequest) Descriptor() ([]byte, []int) {
	return file_auth_teacher_proto_rawDescGZIP(), []int{4}
}

func (x *GetTeacherInformWithUUIDRequest) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *GetTeacherInformWithUUIDRequest) GetTeacherUUID() string {
	if x != nil {
		return x.TeacherUUID
	}
	return ""
}

type GetTeacherInformWithUUIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status      uint32 `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`          // 상태 코드
	Code        int32  `protobuf:"zigzag32,2,opt,name=Code,proto3" json:"Code,omitempty"`            // 세부 코드
	Message     string `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`         // 세부 설명
	Grade       uint32 `protobuf:"varint,4,opt,name=Grade,proto3" json:"Grade,omitempty"`            // 학년 정보
	Class       uint32 `protobuf:"varint,5,opt,name=Class,proto3" json:"Class,omitempty"`            // 반 정보
	Name        string `protobuf:"bytes,6,opt,name=Name,proto3" json:"Name,omitempty"`               // 이름 정보
	PhoneNumber string `protobuf:"bytes,7,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"` // 전화번호 정보
}

func (x *GetTeacherInformWithUUIDResponse) Reset() {
	*x = GetTeacherInformWithUUIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_teacher_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTeacherInformWithUUIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeacherInformWithUUIDResponse) ProtoMessage() {}

func (x *GetTeacherInformWithUUIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_teacher_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeacherInformWithUUIDResponse.ProtoReflect.Descriptor instead.
func (*GetTeacherInformWithUUIDResponse) Descriptor() ([]byte, []int) {
	return file_auth_teacher_proto_rawDescGZIP(), []int{5}
}

func (x *GetTeacherInformWithUUIDResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetTeacherInformWithUUIDResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetTeacherInformWithUUIDResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetTeacherInformWithUUIDResponse) GetGrade() uint32 {
	if x != nil {
		return x.Grade
	}
	return 0
}

func (x *GetTeacherInformWithUUIDResponse) GetClass() uint32 {
	if x != nil {
		return x.Class
	}
	return 0
}

func (x *GetTeacherInformWithUUIDResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetTeacherInformWithUUIDResponse) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type GetTeacherUUIDsWithInformRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Grade       uint32 `protobuf:"varint,1,opt,name=Grade,proto3" json:"Grade,omitempty"`            // 학년 정보
	Class       uint32 `protobuf:"varint,2,opt,name=Class,proto3" json:"Class,omitempty"`            // 반 정보
	Name        string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`               // 이름 정보
	PhoneNumber string `protobuf:"bytes,4,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"` // 전화번호 정보
}

func (x *GetTeacherUUIDsWithInformRequest) Reset() {
	*x = GetTeacherUUIDsWithInformRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_teacher_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTeacherUUIDsWithInformRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeacherUUIDsWithInformRequest) ProtoMessage() {}

func (x *GetTeacherUUIDsWithInformRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_teacher_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeacherUUIDsWithInformRequest.ProtoReflect.Descriptor instead.
func (*GetTeacherUUIDsWithInformRequest) Descriptor() ([]byte, []int) {
	return file_auth_teacher_proto_rawDescGZIP(), []int{6}
}

func (x *GetTeacherUUIDsWithInformRequest) GetGrade() uint32 {
	if x != nil {
		return x.Grade
	}
	return 0
}

func (x *GetTeacherUUIDsWithInformRequest) GetClass() uint32 {
	if x != nil {
		return x.Class
	}
	return 0
}

func (x *GetTeacherUUIDsWithInformRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetTeacherUUIDsWithInformRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type GetTeacherUUIDsWithInformResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status       uint32   `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Code         int32    `protobuf:"zigzag32,2,opt,name=Code,proto3" json:"Code,omitempty"`
	Message      string   `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	TeacherUUIDs []string `protobuf:"bytes,4,rep,name=TeacherUUIDs,proto3" json:"TeacherUUIDs,omitempty"`
}

func (x *GetTeacherUUIDsWithInformResponse) Reset() {
	*x = GetTeacherUUIDsWithInformResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_teacher_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTeacherUUIDsWithInformResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeacherUUIDsWithInformResponse) ProtoMessage() {}

func (x *GetTeacherUUIDsWithInformResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_teacher_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeacherUUIDsWithInformResponse.ProtoReflect.Descriptor instead.
func (*GetTeacherUUIDsWithInformResponse) Descriptor() ([]byte, []int) {
	return file_auth_teacher_proto_rawDescGZIP(), []int{7}
}

func (x *GetTeacherUUIDsWithInformResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetTeacherUUIDsWithInformResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetTeacherUUIDsWithInformResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetTeacherUUIDsWithInformResponse) GetTeacherUUIDs() []string {
	if x != nil {
		return x.TeacherUUIDs
	}
	return nil
}

var File_auth_teacher_proto protoreflect.FileDescriptor

var file_auth_teacher_proto_rawDesc = []byte{
	0x0a, 0x12, 0x61, 0x75, 0x74, 0x68, 0x2d, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x55, 0x0a, 0x17, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x65, 0x61,
	0x63, 0x68, 0x65, 0x72, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1c, 0x0a,
	0x09, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x50, 0x57, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x50, 0x57, 0x22, 0xb4, 0x01, 0x0a, 0x18,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x41, 0x75, 0x74, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x11, 0x52, 0x04,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x30, 0x0a, 0x13, 0x4c, 0x6f, 0x67, 0x67, 0x65, 0x64, 0x49, 0x6e, 0x54, 0x65, 0x61, 0x63,
	0x68, 0x65, 0x72, 0x55, 0x55, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x4c,
	0x6f, 0x67, 0x67, 0x65, 0x64, 0x49, 0x6e, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x55, 0x55,
	0x49, 0x44, 0x22, 0x8c, 0x01, 0x0a, 0x16, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x65, 0x61,
	0x63, 0x68, 0x65, 0x72, 0x50, 0x57, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x55, 0x49,
	0x44, 0x12, 0x20, 0x0a, 0x0b, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x55, 0x55, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x55,
	0x55, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x57,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50,
	0x57, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x57, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x52, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x50,
	0x57, 0x22, 0x5f, 0x0a, 0x17, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x65, 0x61, 0x63, 0x68,
	0x65, 0x72, 0x50, 0x57, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x11, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x57, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x57, 0x69, 0x74, 0x68, 0x55, 0x55, 0x49, 0x44, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x54, 0x65, 0x61,
	0x63, 0x68, 0x65, 0x72, 0x55, 0x55, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x55, 0x55, 0x49, 0x44, 0x22, 0xca, 0x01, 0x0a, 0x20,
	0x47, 0x65, 0x74, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d,
	0x57, 0x69, 0x74, 0x68, 0x55, 0x55, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x11, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x47, 0x72, 0x61, 0x64, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x47, 0x72, 0x61, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x50, 0x68, 0x6f,
	0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x84, 0x01, 0x0a, 0x20, 0x47, 0x65, 0x74,
	0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x55, 0x55, 0x49, 0x44, 0x73, 0x57, 0x69, 0x74, 0x68,
	0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x47, 0x72, 0x61, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x47, 0x72,
	0x61, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22,
	0x8d, 0x01, 0x0a, 0x21, 0x47, 0x65, 0x74, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x55, 0x55,
	0x49, 0x44, 0x73, 0x57, 0x69, 0x74, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x11, 0x52, 0x04, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x54,
	0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x55, 0x55, 0x49, 0x44, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0c, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x55, 0x55, 0x49, 0x44, 0x73, 0x32,
	0xe9, 0x02, 0x0a, 0x0b, 0x41, 0x75, 0x74, 0x68, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x12,
	0x49, 0x0a, 0x10, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x41,
	0x75, 0x74, 0x68, 0x12, 0x18, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x65, 0x61, 0x63, 0x68,
	0x65, 0x72, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x41, 0x75, 0x74, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0f, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x50, 0x57, 0x12, 0x17, 0x2e,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x50, 0x57, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54,
	0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x50, 0x57, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x61, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x57, 0x69, 0x74, 0x68, 0x55, 0x55, 0x49, 0x44, 0x12, 0x20,
	0x2e, 0x47, 0x65, 0x74, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x72,
	0x6d, 0x57, 0x69, 0x74, 0x68, 0x55, 0x55, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x21, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x72, 0x6d, 0x57, 0x69, 0x74, 0x68, 0x55, 0x55, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x64, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x54, 0x65, 0x61, 0x63,
	0x68, 0x65, 0x72, 0x55, 0x55, 0x49, 0x44, 0x73, 0x57, 0x69, 0x74, 0x68, 0x49, 0x6e, 0x66, 0x6f,
	0x72, 0x6d, 0x12, 0x21, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x55,
	0x55, 0x49, 0x44, 0x73, 0x57, 0x69, 0x74, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x65, 0x61, 0x63, 0x68,
	0x65, 0x72, 0x55, 0x55, 0x49, 0x44, 0x73, 0x57, 0x69, 0x74, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x72,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x2e,
	0x3b, 0x61, 0x75, 0x74, 0x68, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_auth_teacher_proto_rawDescOnce sync.Once
	file_auth_teacher_proto_rawDescData = file_auth_teacher_proto_rawDesc
)

func file_auth_teacher_proto_rawDescGZIP() []byte {
	file_auth_teacher_proto_rawDescOnce.Do(func() {
		file_auth_teacher_proto_rawDescData = protoimpl.X.CompressGZIP(file_auth_teacher_proto_rawDescData)
	})
	return file_auth_teacher_proto_rawDescData
}

var file_auth_teacher_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_auth_teacher_proto_goTypes = []interface{}{
	(*LoginTeacherAuthRequest)(nil),           // 0: LoginTeacherAuthRequest
	(*LoginTeacherAuthResponse)(nil),          // 1: LoginTeacherAuthResponse
	(*ChangeTeacherPWRequest)(nil),            // 2: ChangeTeacherPWRequest
	(*ChangeTeacherPWResponse)(nil),           // 3: ChangeTeacherPWResponse
	(*GetTeacherInformWithUUIDRequest)(nil),   // 4: GetTeacherInformWithUUIDRequest
	(*GetTeacherInformWithUUIDResponse)(nil),  // 5: GetTeacherInformWithUUIDResponse
	(*GetTeacherUUIDsWithInformRequest)(nil),  // 6: GetTeacherUUIDsWithInformRequest
	(*GetTeacherUUIDsWithInformResponse)(nil), // 7: GetTeacherUUIDsWithInformResponse
}
var file_auth_teacher_proto_depIdxs = []int32{
	0, // 0: AuthTeacher.LoginTeacherAuth:input_type -> LoginTeacherAuthRequest
	2, // 1: AuthTeacher.ChangeTeacherPW:input_type -> ChangeTeacherPWRequest
	4, // 2: AuthTeacher.GetTeacherInformWithUUID:input_type -> GetTeacherInformWithUUIDRequest
	6, // 3: AuthTeacher.GetTeacherUUIDsWithInform:input_type -> GetTeacherUUIDsWithInformRequest
	1, // 4: AuthTeacher.LoginTeacherAuth:output_type -> LoginTeacherAuthResponse
	3, // 5: AuthTeacher.ChangeTeacherPW:output_type -> ChangeTeacherPWResponse
	5, // 6: AuthTeacher.GetTeacherInformWithUUID:output_type -> GetTeacherInformWithUUIDResponse
	7, // 7: AuthTeacher.GetTeacherUUIDsWithInform:output_type -> GetTeacherUUIDsWithInformResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_teacher_proto_init() }
func file_auth_teacher_proto_init() {
	if File_auth_teacher_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_auth_teacher_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginTeacherAuthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_teacher_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginTeacherAuthResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_teacher_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeTeacherPWRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_teacher_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeTeacherPWResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_teacher_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTeacherInformWithUUIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_teacher_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTeacherInformWithUUIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_teacher_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTeacherUUIDsWithInformRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_teacher_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTeacherUUIDsWithInformResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_auth_teacher_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_teacher_proto_goTypes,
		DependencyIndexes: file_auth_teacher_proto_depIdxs,
		MessageInfos:      file_auth_teacher_proto_msgTypes,
	}.Build()
	File_auth_teacher_proto = out.File
	file_auth_teacher_proto_rawDesc = nil
	file_auth_teacher_proto_goTypes = nil
	file_auth_teacher_proto_depIdxs = nil
}
