// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.1
// 	protoc        v3.11.4
// source: auth-parent.proto

package authproto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type LoginParentAuthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // 학부모용 계정 아이디 (4~16자 사이)
	Pw string `protobuf:"bytes,2,opt,name=pw,proto3" json:"pw,omitempty"` // 학부모용 계정 비밀번호 (4~16자 사이)
}

func (x *LoginParentAuthRequest) Reset() {
	*x = LoginParentAuthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_parent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginParentAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginParentAuthRequest) ProtoMessage() {}

func (x *LoginParentAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_parent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginParentAuthRequest.ProtoReflect.Descriptor instead.
func (*LoginParentAuthRequest) Descriptor() ([]byte, []int) {
	return file_auth_parent_proto_rawDescGZIP(), []int{0}
}

func (x *LoginParentAuthRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LoginParentAuthRequest) GetPw() string {
	if x != nil {
		return x.Pw
	}
	return ""
}

type LoginParentAuthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status      uint32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`                             // 상태 코드
	Code        int32  `protobuf:"zigzag32,2,opt,name=code,proto3" json:"code,omitempty"`                               // 세부 코드
	Message     string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                            // 세부 설명
	AccessToken string `protobuf:"bytes,4,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"` // 학부모 계정 인증을 위한 JWT
	Pid         string `protobuf:"bytes,5,opt,name=pid,proto3" json:"pid,omitempty"`                                    // 로그인한 학부모 계정의 uuid
}

func (x *LoginParentAuthResponse) Reset() {
	*x = LoginParentAuthResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_parent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginParentAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginParentAuthResponse) ProtoMessage() {}

func (x *LoginParentAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_parent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginParentAuthResponse.ProtoReflect.Descriptor instead.
func (*LoginParentAuthResponse) Descriptor() ([]byte, []int) {
	return file_auth_parent_proto_rawDescGZIP(), []int{1}
}

func (x *LoginParentAuthResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *LoginParentAuthResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LoginParentAuthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginParentAuthResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginParentAuthResponse) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

type ChangeParentAuthPwRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid      string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`                            // API를 호출한 학부모 계정의 uuid (20자)
	Pid       string `protobuf:"bytes,2,opt,name=pid,proto3" json:"pid,omitempty"`                              // 변경할 선생님 계정의 uuid (20자)
	CurrentPw string `protobuf:"bytes,3,opt,name=current_pw,json=currentPw,proto3" json:"current_pw,omitempty"` // 해당 사용자의 현재 Pw (4~16 사이)
	NewPw     string `protobuf:"bytes,4,opt,name=new_pw,json=newPw,proto3" json:"new_pw,omitempty"`             // 변경할 Pw (4~16 사이)
}

func (x *ChangeParentAuthPwRequest) Reset() {
	*x = ChangeParentAuthPwRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_parent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeParentAuthPwRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeParentAuthPwRequest) ProtoMessage() {}

func (x *ChangeParentAuthPwRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_parent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeParentAuthPwRequest.ProtoReflect.Descriptor instead.
func (*ChangeParentAuthPwRequest) Descriptor() ([]byte, []int) {
	return file_auth_parent_proto_rawDescGZIP(), []int{2}
}

func (x *ChangeParentAuthPwRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ChangeParentAuthPwRequest) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

func (x *ChangeParentAuthPwRequest) GetCurrentPw() string {
	if x != nil {
		return x.CurrentPw
	}
	return ""
}

func (x *ChangeParentAuthPwRequest) GetNewPw() string {
	if x != nil {
		return x.NewPw
	}
	return ""
}

type ChangeParentAuthPwResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  uint32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`  // 상태 코드
	Code    int32  `protobuf:"zigzag32,2,opt,name=code,proto3" json:"code,omitempty"`    // 세부 코드
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // 세부 설명
}

func (x *ChangeParentAuthPwResponse) Reset() {
	*x = ChangeParentAuthPwResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_parent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeParentAuthPwResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeParentAuthPwResponse) ProtoMessage() {}

func (x *ChangeParentAuthPwResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_parent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeParentAuthPwResponse.ProtoReflect.Descriptor instead.
func (*ChangeParentAuthPwResponse) Descriptor() ([]byte, []int) {
	return file_auth_parent_proto_rawDescGZIP(), []int{3}
}

func (x *ChangeParentAuthPwResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ChangeParentAuthPwResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ChangeParentAuthPwResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetParentUserInformRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // API를 호출한 학부모 계정의 uuid (20자)
	Pid  string `protobuf:"bytes,2,opt,name=pid,proto3" json:"pid,omitempty"`   // 조회할 학부모 계정의 uuid (20자)
}

func (x *GetParentUserInformRequest) Reset() {
	*x = GetParentUserInformRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_parent_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetParentUserInformRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParentUserInformRequest) ProtoMessage() {}

func (x *GetParentUserInformRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_parent_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParentUserInformRequest.ProtoReflect.Descriptor instead.
func (*GetParentUserInformRequest) Descriptor() ([]byte, []int) {
	return file_auth_parent_proto_rawDescGZIP(), []int{4}
}

func (x *GetParentUserInformRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetParentUserInformRequest) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

type GetParentUserInformResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  uint32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`  // 상태 코드
	Code    int32  `protobuf:"zigzag32,2,opt,name=code,proto3" json:"code,omitempty"`    // 세부 코드
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // 세부 설명
	Name    string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`       // 학부모 이름
}

func (x *GetParentUserInformResponse) Reset() {
	*x = GetParentUserInformResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_parent_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetParentUserInformResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParentUserInformResponse) ProtoMessage() {}

func (x *GetParentUserInformResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_parent_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParentUserInformResponse.ProtoReflect.Descriptor instead.
func (*GetParentUserInformResponse) Descriptor() ([]byte, []int) {
	return file_auth_parent_proto_rawDescGZIP(), []int{5}
}

func (x *GetParentUserInformResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetParentUserInformResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetParentUserInformResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetParentUserInformResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_auth_parent_proto protoreflect.FileDescriptor

var file_auth_parent_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x75, 0x74, 0x68, 0x2d, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x38, 0x0a, 0x16, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x72, 0x65,
	0x6e, 0x74, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0e, 0x0a,
	0x02, 0x70, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x70, 0x77, 0x22, 0x94, 0x01,
	0x0a, 0x17, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x41, 0x75, 0x74,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x11, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x70, 0x69, 0x64, 0x22, 0x77, 0x0a, 0x19, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x61,
	0x72, 0x65, 0x6e, 0x74, 0x41, 0x75, 0x74, 0x68, 0x50, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x5f, 0x70, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x50, 0x77, 0x12, 0x15, 0x0a, 0x06, 0x6e, 0x65, 0x77, 0x5f, 0x70, 0x77,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x65, 0x77, 0x50, 0x77, 0x22, 0x62, 0x0a,
	0x1a, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x41, 0x75, 0x74,
	0x68, 0x50, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x11, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x42, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75,
	0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x70, 0x69, 0x64, 0x22, 0x77, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x65,
	0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x11, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0xf9,
	0x01, 0x0a, 0x0a, 0x41, 0x75, 0x74, 0x68, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x46, 0x0a,
	0x0f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x41, 0x75, 0x74, 0x68,
	0x12, 0x17, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x41, 0x75,
	0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x12, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x41, 0x75, 0x74, 0x68, 0x50, 0x77, 0x12, 0x1a, 0x2e, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x41, 0x75, 0x74, 0x68, 0x50, 0x77,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x41, 0x75, 0x74, 0x68, 0x50, 0x77, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x1b, 0x2e,
	0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x47, 0x65, 0x74,
	0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x3b,
	0x61, 0x75, 0x74, 0x68, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_auth_parent_proto_rawDescOnce sync.Once
	file_auth_parent_proto_rawDescData = file_auth_parent_proto_rawDesc
)

func file_auth_parent_proto_rawDescGZIP() []byte {
	file_auth_parent_proto_rawDescOnce.Do(func() {
		file_auth_parent_proto_rawDescData = protoimpl.X.CompressGZIP(file_auth_parent_proto_rawDescData)
	})
	return file_auth_parent_proto_rawDescData
}

var file_auth_parent_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_auth_parent_proto_goTypes = []interface{}{
	(*LoginParentAuthRequest)(nil),      // 0: LoginParentAuthRequest
	(*LoginParentAuthResponse)(nil),     // 1: LoginParentAuthResponse
	(*ChangeParentAuthPwRequest)(nil),   // 2: ChangeParentAuthPwRequest
	(*ChangeParentAuthPwResponse)(nil),  // 3: ChangeParentAuthPwResponse
	(*GetParentUserInformRequest)(nil),  // 4: GetParentUserInformRequest
	(*GetParentUserInformResponse)(nil), // 5: GetParentUserInformResponse
}
var file_auth_parent_proto_depIdxs = []int32{
	0, // 0: AuthParent.LoginParentAuth:input_type -> LoginParentAuthRequest
	2, // 1: AuthParent.ChangeParentAuthPw:input_type -> ChangeParentAuthPwRequest
	4, // 2: AuthParent.GetParentUserInform:input_type -> GetParentUserInformRequest
	1, // 3: AuthParent.LoginParentAuth:output_type -> LoginParentAuthResponse
	3, // 4: AuthParent.ChangeParentAuthPw:output_type -> ChangeParentAuthPwResponse
	5, // 5: AuthParent.GetParentUserInform:output_type -> GetParentUserInformResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_parent_proto_init() }
func file_auth_parent_proto_init() {
	if File_auth_parent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_auth_parent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginParentAuthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_parent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginParentAuthResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_parent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeParentAuthPwRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_parent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeParentAuthPwResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_parent_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetParentUserInformRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_parent_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetParentUserInformResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_auth_parent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_parent_proto_goTypes,
		DependencyIndexes: file_auth_parent_proto_depIdxs,
		MessageInfos:      file_auth_parent_proto_msgTypes,
	}.Build()
	File_auth_parent_proto = out.File
	file_auth_parent_proto_rawDesc = nil
	file_auth_parent_proto_goTypes = nil
	file_auth_parent_proto_depIdxs = nil
}
