# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto.python.auth.auth_student_pb2 as auth__student__pb2


class AuthStudentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LoginStudentAuth = channel.unary_unary(
                '/AuthStudent/LoginStudentAuth',
                request_serializer=auth__student__pb2.LoginStudentAuthRequest.SerializeToString,
                response_deserializer=auth__student__pb2.LoginStudentAuthResponse.FromString,
                )
        self.ChangeStudentPW = channel.unary_unary(
                '/AuthStudent/ChangeStudentPW',
                request_serializer=auth__student__pb2.ChangeStudentPWRequest.SerializeToString,
                response_deserializer=auth__student__pb2.ChangeStudentPWResponse.FromString,
                )
        self.GetStudentInformWithUUID = channel.unary_unary(
                '/AuthStudent/GetStudentInformWithUUID',
                request_serializer=auth__student__pb2.GetStudentInformWithUUIDRequest.SerializeToString,
                response_deserializer=auth__student__pb2.GetStudentInformWithUUIDResponse.FromString,
                )
        self.GetStudentInformsWithUUIDs = channel.unary_unary(
                '/AuthStudent/GetStudentInformsWithUUIDs',
                request_serializer=auth__student__pb2.GetStudentInformsWithUUIDsRequest.SerializeToString,
                response_deserializer=auth__student__pb2.GetStudentInformsWithUUIDsResponse.FromString,
                )
        self.GetStudentUUIDsWithInform = channel.unary_unary(
                '/AuthStudent/GetStudentUUIDsWithInform',
                request_serializer=auth__student__pb2.GetStudentUUIDsWithInformRequest.SerializeToString,
                response_deserializer=auth__student__pb2.GetStudentUUIDsWithInformResponse.FromString,
                )


class AuthStudentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LoginStudentAuth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeStudentPW(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStudentInformWithUUID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStudentInformsWithUUIDs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStudentUUIDsWithInform(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthStudentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LoginStudentAuth': grpc.unary_unary_rpc_method_handler(
                    servicer.LoginStudentAuth,
                    request_deserializer=auth__student__pb2.LoginStudentAuthRequest.FromString,
                    response_serializer=auth__student__pb2.LoginStudentAuthResponse.SerializeToString,
            ),
            'ChangeStudentPW': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeStudentPW,
                    request_deserializer=auth__student__pb2.ChangeStudentPWRequest.FromString,
                    response_serializer=auth__student__pb2.ChangeStudentPWResponse.SerializeToString,
            ),
            'GetStudentInformWithUUID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStudentInformWithUUID,
                    request_deserializer=auth__student__pb2.GetStudentInformWithUUIDRequest.FromString,
                    response_serializer=auth__student__pb2.GetStudentInformWithUUIDResponse.SerializeToString,
            ),
            'GetStudentInformsWithUUIDs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStudentInformsWithUUIDs,
                    request_deserializer=auth__student__pb2.GetStudentInformsWithUUIDsRequest.FromString,
                    response_serializer=auth__student__pb2.GetStudentInformsWithUUIDsResponse.SerializeToString,
            ),
            'GetStudentUUIDsWithInform': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStudentUUIDsWithInform,
                    request_deserializer=auth__student__pb2.GetStudentUUIDsWithInformRequest.FromString,
                    response_serializer=auth__student__pb2.GetStudentUUIDsWithInformResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AuthStudent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AuthStudent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LoginStudentAuth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AuthStudent/LoginStudentAuth',
            auth__student__pb2.LoginStudentAuthRequest.SerializeToString,
            auth__student__pb2.LoginStudentAuthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChangeStudentPW(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AuthStudent/ChangeStudentPW',
            auth__student__pb2.ChangeStudentPWRequest.SerializeToString,
            auth__student__pb2.ChangeStudentPWResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStudentInformWithUUID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AuthStudent/GetStudentInformWithUUID',
            auth__student__pb2.GetStudentInformWithUUIDRequest.SerializeToString,
            auth__student__pb2.GetStudentInformWithUUIDResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStudentInformsWithUUIDs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AuthStudent/GetStudentInformsWithUUIDs',
            auth__student__pb2.GetStudentInformsWithUUIDsRequest.SerializeToString,
            auth__student__pb2.GetStudentInformsWithUUIDsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStudentUUIDsWithInform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AuthStudent/GetStudentUUIDsWithInform',
            auth__student__pb2.GetStudentUUIDsWithInformRequest.SerializeToString,
            auth__student__pb2.GetStudentUUIDsWithInformResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
