# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: club-admin.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='club-admin.proto',
  package='club.admin',
  syntax='proto3',
  serialized_options=b'Z\013.;clubproto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x63lub-admin.proto\x12\nclub.admin\"\x99\x01\n\x14\x43reateNewClubRequest\x12\x0c\n\x04UUID\x18\x01 \x01(\t\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x12\n\nLeaderUUID\x18\x03 \x01(\t\x12\x13\n\x0bMemberUUIDs\x18\x04 \x03(\t\x12\r\n\x05\x46ield\x18\x05 \x01(\t\x12\x10\n\x08Location\x18\x06 \x01(\t\x12\r\n\x05\x46loor\x18\x07 \x01(\t\x12\x0c\n\x04Logo\x18\x08 \x01(\x0c\"X\n\x15\x43reateNewClubResponse\x12\x0e\n\x06Status\x18\x01 \x01(\r\x12\x0c\n\x04\x43ode\x18\x02 \x01(\x11\x12\x0f\n\x07Message\x18\x03 \x01(\t\x12\x10\n\x08\x43lubUUID\x18\x04 \x01(\t2c\n\tClubAdmin\x12V\n\rCreateNewClub\x12 .club.admin.CreateNewClubRequest\x1a!.club.admin.CreateNewClubResponse\"\x00\x42\rZ\x0b.;clubprotob\x06proto3'
)




_CREATENEWCLUBREQUEST = _descriptor.Descriptor(
  name='CreateNewClubRequest',
  full_name='club.admin.CreateNewClubRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='UUID', full_name='club.admin.CreateNewClubRequest.UUID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Name', full_name='club.admin.CreateNewClubRequest.Name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='LeaderUUID', full_name='club.admin.CreateNewClubRequest.LeaderUUID', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MemberUUIDs', full_name='club.admin.CreateNewClubRequest.MemberUUIDs', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Field', full_name='club.admin.CreateNewClubRequest.Field', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Location', full_name='club.admin.CreateNewClubRequest.Location', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Floor', full_name='club.admin.CreateNewClubRequest.Floor', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Logo', full_name='club.admin.CreateNewClubRequest.Logo', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=186,
)


_CREATENEWCLUBRESPONSE = _descriptor.Descriptor(
  name='CreateNewClubResponse',
  full_name='club.admin.CreateNewClubResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Status', full_name='club.admin.CreateNewClubResponse.Status', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Code', full_name='club.admin.CreateNewClubResponse.Code', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Message', full_name='club.admin.CreateNewClubResponse.Message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ClubUUID', full_name='club.admin.CreateNewClubResponse.ClubUUID', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=276,
)

DESCRIPTOR.message_types_by_name['CreateNewClubRequest'] = _CREATENEWCLUBREQUEST
DESCRIPTOR.message_types_by_name['CreateNewClubResponse'] = _CREATENEWCLUBRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateNewClubRequest = _reflection.GeneratedProtocolMessageType('CreateNewClubRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATENEWCLUBREQUEST,
  '__module__' : 'club_admin_pb2'
  # @@protoc_insertion_point(class_scope:club.admin.CreateNewClubRequest)
  })
_sym_db.RegisterMessage(CreateNewClubRequest)

CreateNewClubResponse = _reflection.GeneratedProtocolMessageType('CreateNewClubResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATENEWCLUBRESPONSE,
  '__module__' : 'club_admin_pb2'
  # @@protoc_insertion_point(class_scope:club.admin.CreateNewClubResponse)
  })
_sym_db.RegisterMessage(CreateNewClubResponse)


DESCRIPTOR._options = None

_CLUBADMIN = _descriptor.ServiceDescriptor(
  name='ClubAdmin',
  full_name='club.admin.ClubAdmin',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=278,
  serialized_end=377,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateNewClub',
    full_name='club.admin.ClubAdmin.CreateNewClub',
    index=0,
    containing_service=None,
    input_type=_CREATENEWCLUBREQUEST,
    output_type=_CREATENEWCLUBRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CLUBADMIN)

DESCRIPTOR.services_by_name['ClubAdmin'] = _CLUBADMIN

# @@protoc_insertion_point(module_scope)
