# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto.python.club.club_student_pb2 as club__student__pb2


class ClubStudentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetClubsSortByUpdateTime = channel.unary_unary(
                '/club.admin.ClubStudent/GetClubsSortByUpdateTime',
                request_serializer=club__student__pb2.GetClubsSortByUpdateTimeRequest.SerializeToString,
                response_deserializer=club__student__pb2.GetClubsSortByUpdateTimeResponse.FromString,
                )
        self.GetRecruitmentsSortByCreateTime = channel.unary_unary(
                '/club.admin.ClubStudent/GetRecruitmentsSortByCreateTime',
                request_serializer=club__student__pb2.GetRecruitmentsSortByCreateTimeRequest.SerializeToString,
                response_deserializer=club__student__pb2.GetRecruitmentsSortByCreateTimeResponse.FromString,
                )
        self.GetClubInformWithUUID = channel.unary_unary(
                '/club.admin.ClubStudent/GetClubInformWithUUID',
                request_serializer=club__student__pb2.GetClubInformWithUUIDRequest.SerializeToString,
                response_deserializer=club__student__pb2.GetClubInformWithUUIDResponse.FromString,
                )
        self.GetClubInformsWithUUIDs = channel.unary_unary(
                '/club.admin.ClubStudent/GetClubInformsWithUUIDs',
                request_serializer=club__student__pb2.GetClubInformsWithUUIDsRequest.SerializeToString,
                response_deserializer=club__student__pb2.GetClubInformsWithUUIDsResponse.FromString,
                )
        self.GetRecruitmentInformWithUUID = channel.unary_unary(
                '/club.admin.ClubStudent/GetRecruitmentInformWithUUID',
                request_serializer=club__student__pb2.GetRecruitmentInformWithUUIDRequest.SerializeToString,
                response_deserializer=club__student__pb2.GetRecruitmentInformWithUUIDResponse.FromString,
                )
        self.GetRecruitmentUUIDWithClubUUID = channel.unary_unary(
                '/club.admin.ClubStudent/GetRecruitmentUUIDWithClubUUID',
                request_serializer=club__student__pb2.GetRecruitmentUUIDWithClubUUIDRequest.SerializeToString,
                response_deserializer=club__student__pb2.GetRecruitmentUUIDWithClubUUIDResponse.FromString,
                )
        self.GetRecruitmentUUIDsWithClubUUIDs = channel.unary_unary(
                '/club.admin.ClubStudent/GetRecruitmentUUIDsWithClubUUIDs',
                request_serializer=club__student__pb2.GetRecruitmentUUIDsWithClubUUIDsRequest.SerializeToString,
                response_deserializer=club__student__pb2.GetRecruitmentUUIDsWithClubUUIDsResponse.FromString,
                )
        self.GetAllClubFields = channel.unary_unary(
                '/club.admin.ClubStudent/GetAllClubFields',
                request_serializer=club__student__pb2.GetAllClubFieldsRequest.SerializeToString,
                response_deserializer=club__student__pb2.GetAllClubFieldsResponse.FromString,
                )
        self.GetTotalCountOfClubs = channel.unary_unary(
                '/club.admin.ClubStudent/GetTotalCountOfClubs',
                request_serializer=club__student__pb2.GetTotalCountOfClubsRequest.SerializeToString,
                response_deserializer=club__student__pb2.GetTotalCountOfClubsResponse.FromString,
                )
        self.GetTotalCountOfCurrentRecruitments = channel.unary_unary(
                '/club.admin.ClubStudent/GetTotalCountOfCurrentRecruitments',
                request_serializer=club__student__pb2.GetTotalCountOfCurrentRecruitmentsRequest.SerializeToString,
                response_deserializer=club__student__pb2.GetTotalCountOfCurrentRecruitmentsResponse.FromString,
                )
        self.GetClubUUIDWithLeaderUUID = channel.unary_unary(
                '/club.admin.ClubStudent/GetClubUUIDWithLeaderUUID',
                request_serializer=club__student__pb2.GetClubUUIDWithLeaderUUIDRequest.SerializeToString,
                response_deserializer=club__student__pb2.GetClubUUIDWithLeaderUUIDResponse.FromString,
                )
        self.GetClubUUIDsWithFloor = channel.unary_unary(
                '/club.admin.ClubStudent/GetClubUUIDsWithFloor',
                request_serializer=club__student__pb2.GetClubUUIDsWithFloorRequest.SerializeToString,
                response_deserializer=club__student__pb2.GetClubUUIDsWithFloorResponse.FromString,
                )


class ClubStudentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetClubsSortByUpdateTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecruitmentsSortByCreateTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClubInformWithUUID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClubInformsWithUUIDs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecruitmentInformWithUUID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecruitmentUUIDWithClubUUID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecruitmentUUIDsWithClubUUIDs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllClubFields(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTotalCountOfClubs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTotalCountOfCurrentRecruitments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClubUUIDWithLeaderUUID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClubUUIDsWithFloor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClubStudentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetClubsSortByUpdateTime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClubsSortByUpdateTime,
                    request_deserializer=club__student__pb2.GetClubsSortByUpdateTimeRequest.FromString,
                    response_serializer=club__student__pb2.GetClubsSortByUpdateTimeResponse.SerializeToString,
            ),
            'GetRecruitmentsSortByCreateTime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecruitmentsSortByCreateTime,
                    request_deserializer=club__student__pb2.GetRecruitmentsSortByCreateTimeRequest.FromString,
                    response_serializer=club__student__pb2.GetRecruitmentsSortByCreateTimeResponse.SerializeToString,
            ),
            'GetClubInformWithUUID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClubInformWithUUID,
                    request_deserializer=club__student__pb2.GetClubInformWithUUIDRequest.FromString,
                    response_serializer=club__student__pb2.GetClubInformWithUUIDResponse.SerializeToString,
            ),
            'GetClubInformsWithUUIDs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClubInformsWithUUIDs,
                    request_deserializer=club__student__pb2.GetClubInformsWithUUIDsRequest.FromString,
                    response_serializer=club__student__pb2.GetClubInformsWithUUIDsResponse.SerializeToString,
            ),
            'GetRecruitmentInformWithUUID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecruitmentInformWithUUID,
                    request_deserializer=club__student__pb2.GetRecruitmentInformWithUUIDRequest.FromString,
                    response_serializer=club__student__pb2.GetRecruitmentInformWithUUIDResponse.SerializeToString,
            ),
            'GetRecruitmentUUIDWithClubUUID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecruitmentUUIDWithClubUUID,
                    request_deserializer=club__student__pb2.GetRecruitmentUUIDWithClubUUIDRequest.FromString,
                    response_serializer=club__student__pb2.GetRecruitmentUUIDWithClubUUIDResponse.SerializeToString,
            ),
            'GetRecruitmentUUIDsWithClubUUIDs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecruitmentUUIDsWithClubUUIDs,
                    request_deserializer=club__student__pb2.GetRecruitmentUUIDsWithClubUUIDsRequest.FromString,
                    response_serializer=club__student__pb2.GetRecruitmentUUIDsWithClubUUIDsResponse.SerializeToString,
            ),
            'GetAllClubFields': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllClubFields,
                    request_deserializer=club__student__pb2.GetAllClubFieldsRequest.FromString,
                    response_serializer=club__student__pb2.GetAllClubFieldsResponse.SerializeToString,
            ),
            'GetTotalCountOfClubs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTotalCountOfClubs,
                    request_deserializer=club__student__pb2.GetTotalCountOfClubsRequest.FromString,
                    response_serializer=club__student__pb2.GetTotalCountOfClubsResponse.SerializeToString,
            ),
            'GetTotalCountOfCurrentRecruitments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTotalCountOfCurrentRecruitments,
                    request_deserializer=club__student__pb2.GetTotalCountOfCurrentRecruitmentsRequest.FromString,
                    response_serializer=club__student__pb2.GetTotalCountOfCurrentRecruitmentsResponse.SerializeToString,
            ),
            'GetClubUUIDWithLeaderUUID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClubUUIDWithLeaderUUID,
                    request_deserializer=club__student__pb2.GetClubUUIDWithLeaderUUIDRequest.FromString,
                    response_serializer=club__student__pb2.GetClubUUIDWithLeaderUUIDResponse.SerializeToString,
            ),
            'GetClubUUIDsWithFloor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClubUUIDsWithFloor,
                    request_deserializer=club__student__pb2.GetClubUUIDsWithFloorRequest.FromString,
                    response_serializer=club__student__pb2.GetClubUUIDsWithFloorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'club.admin.ClubStudent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClubStudent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetClubsSortByUpdateTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/club.admin.ClubStudent/GetClubsSortByUpdateTime',
            club__student__pb2.GetClubsSortByUpdateTimeRequest.SerializeToString,
            club__student__pb2.GetClubsSortByUpdateTimeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRecruitmentsSortByCreateTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/club.admin.ClubStudent/GetRecruitmentsSortByCreateTime',
            club__student__pb2.GetRecruitmentsSortByCreateTimeRequest.SerializeToString,
            club__student__pb2.GetRecruitmentsSortByCreateTimeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetClubInformWithUUID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/club.admin.ClubStudent/GetClubInformWithUUID',
            club__student__pb2.GetClubInformWithUUIDRequest.SerializeToString,
            club__student__pb2.GetClubInformWithUUIDResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetClubInformsWithUUIDs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/club.admin.ClubStudent/GetClubInformsWithUUIDs',
            club__student__pb2.GetClubInformsWithUUIDsRequest.SerializeToString,
            club__student__pb2.GetClubInformsWithUUIDsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRecruitmentInformWithUUID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/club.admin.ClubStudent/GetRecruitmentInformWithUUID',
            club__student__pb2.GetRecruitmentInformWithUUIDRequest.SerializeToString,
            club__student__pb2.GetRecruitmentInformWithUUIDResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRecruitmentUUIDWithClubUUID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/club.admin.ClubStudent/GetRecruitmentUUIDWithClubUUID',
            club__student__pb2.GetRecruitmentUUIDWithClubUUIDRequest.SerializeToString,
            club__student__pb2.GetRecruitmentUUIDWithClubUUIDResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRecruitmentUUIDsWithClubUUIDs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/club.admin.ClubStudent/GetRecruitmentUUIDsWithClubUUIDs',
            club__student__pb2.GetRecruitmentUUIDsWithClubUUIDsRequest.SerializeToString,
            club__student__pb2.GetRecruitmentUUIDsWithClubUUIDsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllClubFields(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/club.admin.ClubStudent/GetAllClubFields',
            club__student__pb2.GetAllClubFieldsRequest.SerializeToString,
            club__student__pb2.GetAllClubFieldsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTotalCountOfClubs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/club.admin.ClubStudent/GetTotalCountOfClubs',
            club__student__pb2.GetTotalCountOfClubsRequest.SerializeToString,
            club__student__pb2.GetTotalCountOfClubsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTotalCountOfCurrentRecruitments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/club.admin.ClubStudent/GetTotalCountOfCurrentRecruitments',
            club__student__pb2.GetTotalCountOfCurrentRecruitmentsRequest.SerializeToString,
            club__student__pb2.GetTotalCountOfCurrentRecruitmentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetClubUUIDWithLeaderUUID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/club.admin.ClubStudent/GetClubUUIDWithLeaderUUID',
            club__student__pb2.GetClubUUIDWithLeaderUUIDRequest.SerializeToString,
            club__student__pb2.GetClubUUIDWithLeaderUUIDResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetClubUUIDsWithFloor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/club.admin.ClubStudent/GetClubUUIDsWithFloor',
            club__student__pb2.GetClubUUIDsWithFloorRequest.SerializeToString,
            club__student__pb2.GetClubUUIDsWithFloorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
