# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto.python.club.club_admin_pb2 as club__admin__pb2


class ClubAdminStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateNewClub = channel.unary_unary(
                '/club.admin.ClubAdmin/CreateNewClub',
                request_serializer=club__admin__pb2.CreateNewClubRequest.SerializeToString,
                response_deserializer=club__admin__pb2.CreateNewClubResponse.FromString,
                )


class ClubAdminServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateNewClub(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClubAdminServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateNewClub': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNewClub,
                    request_deserializer=club__admin__pb2.CreateNewClubRequest.FromString,
                    response_serializer=club__admin__pb2.CreateNewClubResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'club.admin.ClubAdmin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClubAdmin(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateNewClub(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/club.admin.ClubAdmin/CreateNewClub',
            club__admin__pb2.CreateNewClubRequest.SerializeToString,
            club__admin__pb2.CreateNewClubResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
